간단 카운터 앱 (파일 분리)
CodeSoom/react-week2-assignment-1 pull request #170
Opened 2022-08-08 12:02 UTC by 0-Chan

안녕하세요! 아직 미완성이지만 한번 미리 PR 요청드립니다.

비가 정말 많이 오는데 조심하시구요~~ 완성되면 commit 마저 드리겠습니다.ㅎㅎ

2022-08-08 14:16 UTC, daadaadaah requested changes
월요일부터 PR 날리신 점 너무 잘하셨습니다!👏
App 컴포넌트는 지금 작업 중이신 것 같으니, 다음 commit 때 한번 더 볼게요~!😊

2022-08-08 14:16 UTC, daadaadaah commented on src/Button.jsx
> +import React from 'react';
react 17 버전부터 이부분 생략 가능해요!
현재 리액트 버전 확인하시구~ 적용시켜보세요!
참고 : https://ko.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#whats-different-in-the-new-transform

2022-08-08 14:16 UTC, daadaadaah commented on src/Buttons.jsx
> +
삭제해주시는 거 깜박하신것 같아요!ㅎㅎ

2022-08-08 14:16 UTC, daadaadaah commented on src/index.jsx
> +// App
이렇게 어떻게 나눌 것인지 미리 생각해보는거 너무 좋은 프로세스인것 같아요!ㅎㅎ
다만, 추후에 주석은 깔끔하게 정리해주시면 좋을 것 같아요!ㅎㅎ

2022-08-08 14:16 UTC, daadaadaah commented on src/Button.jsx
> +export default function Button({ children }) {
onClick props가 빠진 것 같아요!ㅎㅎ

2022-08-08 14:16 UTC, daadaadaah commented on src/Buttons.jsx
> +    <p>
그냥 Fragment로 써도 되지 않을까요?ㅎㅎ

2022-08-08 14:16 UTC, daadaadaah commented on src/Counter.jsx
> +    <button type="button" onClick={onClick}>
컴포넌트는 보통 대문자를 사용합니다!

2022-08-09 03:02 UTC, 0-Chan commented on src/Button.jsx
> +import React from 'react';
헉 친절히 남겨주신 링크 따라서 `import React from 'react';` 문구는 모두 삭제했습니다!!
훨씬 깔끔한 느낌이 드네요.ㅎㅎ

2022-08-09 03:03 UTC, 0-Chan commented on src/Buttons.jsx
> +
앞으로 주석, 잡다한 코드는 꼭 정돈해서 PR 드리도록 하겠습니다..!😅

2022-08-09 03:04 UTC, 0-Chan commented on src/Counter.jsx
> +    <button type="button" onClick={onClick}>
이건 제가 놓쳤네요 ㅜㅜ 꼼꼼하게 봐주셔서 감사합니다!

2022-08-09 03:06 UTC, 0-Chan commented on src/Button.jsx
> +export default function Button({ children }) {
넵! 이 부분 수정하고 아래에 arrow function으로 onClick을 호출 하는 방식으로 `<Buttons/>`를 완성했습니다.

2022-08-09 12:11 UTC, daadaadaah requested changes
잘하셨어요!👏 변수명만 하나 수정해주시고~ 다음 과제 진행해주시면 될 것 같아요!ㅎㅎ

2022-08-09 12:11 UTC, daadaadaah commented on src/App.jsx
> +  function handleClick(keyValue) {
`keyValue` 라는 변수명 보다 좀더 의도가 드러나는 변수명은 없을까용?ㅎㅎ🤔

2022-08-10 11:50 UTC, 0-Chan commented on src/App.jsx
> +  function handleClick(keyValue) {
오옷.. `addValue` 라는 이름으로 바꾸어 직관적으로 무슨 역할인지 알 수 있게끔 하였습니다!

2022-08-10 11:52 UTC, 0-Chan commented
> 잘하셨어요!clap 변수명만 하나 수정해주시고~ 다음 과제 진행해주시면 될 것 같아요!ㅎㅎ

감사합니다~! Todo 앱 작업 중에 있는데.. 꼬인 부분이 있어 다음에 PR 드리도록 하겠습니다^^
좋은 저녁 보내세요~~

2022-08-10 13:33 UTC, daadaadaah approved these changes
수고하셨습니다!👏

2022-08-10 13:33 UTC, daadaadaah commented on src/App.jsx
> +      count: count + addValue,
동사+명사는 주로 함수 네이밍할 때 사용하므로, 수동태+명사 또는 형용사+명사 이런 형태(예 : `addedValue`)로 변수를 네이밍하는 것이 더 좋아요!

2022-08-15 03:30 UTC, merged