간단한 카운터앱 만들고 파일 분리
CodeSoom/react-week2-assignment-1 pull request #172
Opened 2022-08-09 11:59 UTC by ChoJinmok

## :: 최근 작업 주제
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표
- 간단한 카운터앱 만들고 파일 분리
<br />

## :: 구현 사항 설명
- 1차 제출 - 강의 듣고 만든 counter앱에서 파일분리
  - state, 컴포넌트, 변수 명 등을 좀더 명확한 이름으로 변경
<br />

## :: 기타 질문 및 특이 사항
- 강의에서는 handleClick을 props로 전달해줄 때 onClick으로 전달해주는데

2022-08-09 14:05 UTC, daadaadaah requested changes
> 강의에서는 handleClick을 props로 전달해줄 때 onClick으로 전달해주는데 onClick은 이름이 너무 포괄적이라는 느낌이 들어서요~ onClick으로 그냥 전달해주는 경우가 많나요?~🤔
- 팀에서 어떻게 결정하느냐에 따라 다를 것 같아요!ㅎㅎ 아샬님은 onClick, onChange 이렇게 코딩하시는 걸 선호하시는 것 같아요!

> 파일 분리할 때 App까지 분리해주는게 좋은 걸까요?~
- 컴포넌트를 분리할 때, 최대한 작게 쪼개는것보다 '왜' 나누는지가 더 중요해요!
- App 분리시켜줬을 때와 그렇지 않을 때, 어떤게 더 나을지 한번 생각해보세요!
- 굳이 나눠줘야하나? 아니면 나눴을 때 이런게 좋다! 등 한번 생각해봅시당!

2022-08-09 14:05 UTC, daadaadaah commented on src/Counter/App.jsx
> +}
항상 Pull Request를 보내고 나서 자신이 작성한 코드를 Files changed 에서 다시 한번 살펴보는 습관을 들이시길 추천합니다! 파일 끝에 개행을 추가하지 않으면 파일 끝에 ⛔️ (No newline at end of file) 경고 문구가 붙어요. 따라서, 마지막 한줄은 띄어주시는게 좋아요!ㅎㅎ

2022-08-09 14:05 UTC, daadaadaah commented on src/index.jsx
> +import CounterApp from './Counter/App'
Counter라는 폴더를 만드신 특별한 이유가 있으신가요?

2022-08-09 14:05 UTC, daadaadaah commented on src/Counter/App.jsx
> +        buttonClick={handleClick}
저는 직접적으로 로직을 처리하는 이벤트 핸들러 함수의 경우 handleXXX 으로 함수 이름을 정하고,
중간에 전달하는 역할 정도만 하는 props 같은 이름으로 사용할 때는 onXXX 으로 사용하는 편이에요. 
왜냐하면, 실제 일을 `처리`하는 관점과 `사용`하는 입장에서 바라볼 때의 의도를 각각 드러내줄 수 있기 때문이예요! 같이 읽어보면 좋은 링크 하나 첨부해요~ 한번 읽어보세요!

참고:
- [https://javascript.plainenglish.io/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364](https://javascript.plainenglish.io/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364)

2022-08-10 07:15 UTC, ChoJinmok commented on src/Counter/App.jsx
> +}
아~~ 앞으로는 Files changed까지 체크하는 습관을 들여야겠네요~!
좋은 리뷰 감사합니다👏

2022-08-10 07:17 UTC, ChoJinmok commented on src/index.jsx
> +import CounterApp from './Counter/App'
🙂당장엔 Counter앱 밖에 없지만 다른 앱도 추가될 수도 있다고 생각해 이게 더 확장성이 있다고 생각했습니다!!

2022-08-10 09:05 UTC, ChoJinmok commented on src/Counter/App.jsx
> +        buttonClick={handleClick}
특정한 규친을 정해놓고 네이밍을 하는게 훨씬 장점이 많겠네요!! 좋은리뷰 감사해요☺️

2022-08-10 09:16 UTC, ChoJinmok commented on src/Counter/App.jsx
> +      onButtonClick={handleButtonClick}
App.jsx에 CounterPage컴포넌트에 Eslint 경고가 떴었는데 윤석님께서 8주차 메모이제이션에대해 공부하고 다시 확인해보면 좋겠다하셔서 일단 disable해줬습니다!

2022-08-10 14:03 UTC, daadaadaah commented on src/Counter/App.jsx
> +      onButtonClick={handleButtonClick}
보통 `on+동사+(명사)` 형태로 네이밍합니다!ㅎㅎ

2022-08-10 14:03 UTC, daadaadaah commented on src/index.jsx
> +import CounterApp from './Counter/App'
확장성까지 고려하신 점은 잘하셨지만, 폴더 및 파일 구조 잡으실 때, import 시 뎁스도 고려하시면 좋을 것 같아요!ㅎㅎ
폴더에 모아서 관리하는 것도 좋지만, 폴더 안에 넣음으로써, import `../.../../` 이런식으로 복잡해질 수 있으니, 이런 부분도 한번 고려해보세요!

2022-08-10 14:05 UTC, ChoJinmok commented on src/Counter/App.jsx
> +      onButtonClick={handleButtonClick}
앗..!ㅎㅎ 고민했었는데 감사합니당~!

2022-08-10 14:13 UTC, ChoJinmok reviewed
import 뎁스까지는 고려를 못했었네요 😭
확실히 뎁스가 깊어질 때 단점이 생기는 것 같습니다!
좋은 리뷰 감사합니다!

2022-08-10 14:15 UTC, ChoJinmok commented on src/index.jsx
> +import CounterApp from './Counter/App'
import 뎁스까지는 고려를 못했었네요 😭
확실히 뎁스가 깊어질 때 단점이 생기는 것 같습니다!
좋은 리뷰 감사합니다!

2022-08-10 15:45 UTC, daadaadaah approved these changes
수고하셨어요!ㅎㅎ
이번주 피드백 강의를 보며 아샬님은 어떻게 구현하셨는지 한번 살펴보세요!ㅎㅎ

2022-08-15 03:31 UTC, merged