Counter 앱 만들고 파일 분리하기
CodeSoom/react-week2-assignment-1 pull request #174
Opened 2022-08-11 12:56 UTC by violet4795

- 파일 분리
- onClick 을 변수형태로 쭉 props drilling...

2022-08-11 12:57 UTC, violet4795 commented
Buttons와 Button 이 좀 고민되었는데,
Button html을 만드는 작업을 하는 컴포넌트와 
Button컴포넌트를 생성해주는 사용자 컴포넌트라고 생각해서 나눴습니당

2022-08-12 12:19 UTC, daadaadaah requested changes
컴포넌트 파일 이름은 보통 대문자로 사용합니다! 한번 체크해주세요😄

2022-08-12 12:19 UTC, daadaadaah commented on src/button.jsx
> +    <button type="button" onClick={() => onClick(children)}>
Button 컴포넌트에서 해주는 것과
```jsx
<button type="button" onClick={() => onClick(children)}>
```
Buttons 컴폰넌트에서 해주는 것의 차이에 대해 한번 생각해보세요!

```jsx
// Buttons.jsx
{[1, 2, 3, 4, 5].map((i) => (
  <Button key={i} onClick={() => onClick(i)}>
    {i}
  </Button>
))}

// Button.jsx
<button type="button" onClick={() => onClick(children)}>
```

2022-08-12 12:20 UTC, daadaadaah requested changes

2022-08-12 12:20 UTC, daadaadaah commented on src/button.jsx
> +import React from 'react';
react 17 버전부터 이부분 생략 가능해요!
현재 리액트 버전 확인하시구~ 적용시켜보세요!
참고 : https://ko.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#whats-different-in-the-new-transform

2022-08-12 12:20 UTC, daadaadaah commented on src/buttons.jsx
> +import Button from './button';
맥락 구분을 위해 한줄 띄어줍시당!ㅎㅎ

2022-08-12 12:20 UTC, daadaadaah commented on src/index.jsx
> +import Page from './page';
여기도 띄어줍시당!ㅎㅎ

2022-08-12 12:20 UTC, daadaadaah commented on src/page.jsx
> +import Counter from './counter';
여기도요!ㅎㅎ

2022-08-15 03:30 UTC, merged