assignment1- Counter앱, 파일분리
CodeSoom/react-week2-assignment-1 pull request #181
Opened 2022-10-19 00:36 UTC by hyeji07

### 내용

- Counter 앱 만들기
- 컴포넌트 파일 분리 하기

### 스크린샷
![2022-10-19 09 34 54](https://user-images.githubusercontent.com/108104436/196570115-f21ac492-4349-44b6-a329-f7fd09acc006.gif)

2022-10-20 05:06 UTC, daadaadaah requested changes
과제2까지 후딱 수행하셨네용! 잘하셨어요!👏 
남겨드린 코멘트 한번 참고해보세요!ㅎㅎ

2022-10-20 05:06 UTC, daadaadaah commented on src/components/buttons/Buttons.jsx
> +  return (
맥락 구분을 위해 한줄 띄어줍시당!

2022-10-20 05:06 UTC, daadaadaah commented on src/index.jsx
> +import App from './App';
맥락 구분을 위해 한줄 띄어줍시당!

2022-10-20 05:06 UTC, daadaadaah commented on src/pages/CounterPage.jsx
> +function CounterPage({ count, onClick, handleClickNumber }) {
[과제2 에서 드린 코멘트](https://github.com/CodeSoom/react-week2-assignment-2/pull/165#discussion_r1000144676) 참고해주세요!ㅎㅎ

2022-10-20 05:06 UTC, daadaadaah commented on src/components/Counter.jsx
> +import React from 'react';
리액트17 버전 이후부터는 생략이 가능해요!
사용하시는 리액트 버전을 확인하신 후 적용해보시면 좋을 것 같아요.
참고:
React 공홈
https://ko.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#whats-different-in-the-new-transform
기존 JSX 변환과 현재 JSX 변환의 차이점이 잘 나온 링크
https://blog.saeloun.com/2021/07/01/react-17-adds-jsx-runtime-and-jsx-dev-runtime-for-the-new-jsx-transform

2022-10-20 08:05 UTC, hyeji07 commented on src/index.jsx
> +import App from './App';
![image](https://user-images.githubusercontent.com/108104436/196892148-ac119dd0-b299-489c-9536-7412b2edf9ef.png)

이 경우 이렇게 띄어주면 되는 건가요?

2022-10-20 09:09 UTC, hyeji07 commented on src/components/Counter.jsx
> +import React from 'react';
생략하니까 편하네요..! 😳
실행되는데 방법이 맞는지 확인하고 싶어서요!
생략 후 babel 파일에 이렇게만 변경하면 되는 것 맞나요?

`module.exports = {
  presets: [
    [
      '@babel/preset-react', {
        runtime: 'automatic',
      },
    ],
  ],
};
`

2022-10-20 10:00 UTC, hyeji07 commented on src/pages/CounterPage.jsx
> +function CounterPage({ count, onClick, handleClickNumber }) {
Props Drilling을 해결 하기 위해 
App.jsx에서 선언했던 state와 함수를 사용되는 CounterPage.jsx 로 옮겼습니다.  이렇게 수정한 방법이 괜찮은가요?

2022-10-20 10:02 UTC, hyeji07 commented
리뷰에 따라 다시 수정 후 Commit 하였습니다 !

2022-10-21 04:53 UTC, daadaadaah approved these changes
잘하셨어요!👏 아샬님 피드백 강의를 들으면 아샬님은 어떻게 하셨는지 잘 관찰해보세요!ㅎㅎ

2022-10-21 08:04 UTC, hyeji07 commented
넵 감사합니당 😃

2022-10-25 12:37 UTC, merged