2주차 - 관심사의 분리 구현 사항 PR올립니다!
CodeSoom/react-week2-assignment-1 pull request #182
Opened 2022-12-12 11:50 UTC by Ubermensch0608

안녕하세요 트레이너님! 즐거운 한 주의 시작이네요 :)

관심사의 분리를 신경쓰면서 카운터 기능 구현해봤습니다.

UI 컴포넌트와 비즈니스 로직 컴포넌트를 나누어 어떤 기능이 추가, 삭제, 변경이 될지 모르는 미래에 대비할 수 있다는 점은 공감이 되었고,
깔끔하게 유지할 수 있어 저도 지양해야하는 부분이라고 생각합니다!
다만, 한 가지 궁금한 사항은 실제 웹 서비스를 만들 경우 서비스가 커지면 커질 수록 분리된 수 많은 컴포넌트와 로직들이 때로는 혼란을 주는 때도 있는 것 같습니다.  본 과제에서 구현한 기능은 간단하기때문에 눈에 잘 들어오는 느낌이 들지만, 조금만 커져도 무언가 복잡해지는 폴더 구조가 항상 고민이 되었습니다.

좋은 폴더 구조와 이름으로 관리하면 앱 규모가 커지더라도 복잡하지 않은 것이 정상일까요? 아니면,  그 정도가 된다면 프로젝트를 따로 나누어 관리하는 것이 좋은 것일까요? 

피드백 기다리겠습니다. 감사합니다!

2022-12-12 13:36 UTC, daadaadaah requested changes
> 좋은 폴더 구조와 이름으로 관리하면 앱 규모가 커지더라도 복잡하지 않은 것이 정상일까요? 아니면, 그 정도가 된다면 프로젝트를 따로 나누어 관리하는 것이 좋은 것일까요?

- 폴더 구조 및 이름은 언제나 고민되는 부부인 것 같아요! 먼저, "좋다"라는 의미가 팀마다 다르고 비즈니스 상황마다 다를 수 있다고 생각하는데, 프로젝트를 따로 나누어 관리하는게 좋은지 여부는 같이 일하는 동료와 정해서 결론을 내리므로, 정답은 없다고 생각해요! 어느 팀에서는 A라는 폴더구조가 복잡하다고 느낄 있고, 어떤 팀에서는 A라는 폴더구조가 단순하다고 느낄 수 있기 때문이죠! 따라서, 정답인 폴더구조가 무엇인지 보다 팀 동료와 좋은 폴더구조를 찾아가는 과정이 좀더 의미 있는 일이 아닐까 생각해요!
- 읽어보면 도움될만한 리액트 공식 홈페이지 자료 첨부합니다
- 참고 : https://reactjs.org/docs/faq-structure.html

2022-12-12 13:36 UTC, daadaadaah commented on src/components/counter/Button.jsx
> +import React from 'react'
리액트17 버전 이후부터는 생략이 가능해요!
사용하시는 리액트 버전을 확인하신 후 적용해보시면 좋을 것 같아요.
참고:
- https://ko.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#whats-different-in-the-new-transform
- https://blog.saeloun.com/2021/07/01/react-17-adds-jsx-runtime-and-jsx-dev-runtime-for-the-new-jsx-transform

2022-12-12 13:36 UTC, daadaadaah commented on src/components/counter/Button.jsx
> +           {children} {incrementValue}
`children`과 `incrementValue` 어떤 차이를 두고 만드셨나요?

2022-12-12 13:36 UTC, daadaadaah commented on src/components/counter/Buttons.jsx
> +const Buttons = ({onIncrement}) => {
보통 `on+명사`보다 `on+동사`로 표현합니다ㅎㅎ

2022-12-12 13:36 UTC, daadaadaah commented on src/components/pages/CounterPage.jsx
> +}
지금 `CounterPage`가 있을 때와 없을 때(=`CounterPage`의 역할을 `App`에서 하기)에 애플리케이션을 이해하는데 큰 어려움이 있을까요?

2022-12-12 20:52 UTC, Ubermensch0608 commented on src/components/counter/Button.jsx
> +import React from 'react'
알려주신 자료 참고해서 babel.config.js 수정하고 
불필요한 import React from 'react' 구문 생략했습니다!

vscode 확장에서 react code snippets 사용하여 위 구문이 항상 추가되었었는데 vscode 세팅에서 생기지 않도록 설정도 완료했습니다 :)

2022-12-12 20:56 UTC, Ubermensch0608 commented on src/components/pages/CounterPage.jsx
> +}
관심사의 분리에 초점을 맞추다 보니 Counter 기능을 담당하는 페이지를 나누는 것이 좋겠다고 생각이 들었네요.
지금 처럼 하나의 기능만 있고 라우팅이 구현되어 있지 않은 애플리케이션에서는 CounterPage 없이 App 으로만으로도 이해가 어렵지는 않을 거 같아요!

2022-12-12 21:02 UTC, Ubermensch0608 commented on src/components/counter/Buttons.jsx
> +const Buttons = ({onIncrement}) => {
함수의 전달을 의미하는 props는 on+동사
함수는 동사 + 명사 조합으로 네이밍하는 것을 잊지 않고 실천해보겠습니다ㅎㅎ

2022-12-12 21:30 UTC, Ubermensch0608 commented on src/components/counter/Button.jsx
> +           {children} {incrementValue}
incrementValue는 버튼을 클릭했을 때 어느 정도의 값만큼 변화를 줄 것인지를 담당하도록 하였습니다. 
예를 들어, <Button incrementValue={x} /> 버튼 컴포넌트에 x의 값이 올라갈 것임을 명시하면 버튼을 눌렀을 때 해당 값만큼 counter가 증가합니다. 
 
'어떠한 값을 더한다' 라는 공통적인 기능은  고정시켜두고, 변할 수 있는 더해지는 값은 Button 컴포넌트를 사용할 때마다 커스텀 할 수 있도록 하였습니다. 이는 원하는 값을 증가시키는 함수를 일일이 만들지 않고 값을 명시하는 것 만으로도 컴포넌트 및 함수를 재사용할 수 있다는 점에서 이점이 있다고 생각합니다! (incrementValue에 값이 명시되어있지 않을 경우는 +1만큼 증가하는 것을 default로 이용하게끔 increaseCount 함수에 세팅하였습니다.)

children은 'Click me! (0)' 버튼과 같이 ...

어떤 차이가 있는지 설명하다보니 incrementValue가 올리는 값을 담당하는 것이면 children과 함께 나올 이유가 없지 않나 생각이 들었고 children만으로 표현할 수 있음을 깨달았습니다.  
오히려 <Button /> 컴포넌트와 같이 재사용 가능성이 높은 녀석들은 incrementValue를 같이 두었을 때 원치 않은 ui가 나타날 수 있을 거 같네요. 짚어주셔서 감사합니다!

2022-12-13 10:22 UTC, Ubermensch0608 commented
말씀해주신 피드백 반영해서 커밋 최신화 했습니다~

2022-12-13 15:58 UTC, Ubermensch0608 reviewed
말씀하신 피드백 반영해서 커밋 완료했습니다~!

2022-12-14 04:09 UTC, daadaadaah requested changes

2022-12-14 04:09 UTC, daadaadaah commented on src/components/counter/Counter.jsx
> +  };
비즈니스 로직을 `App`에서 관리하는 것과 `Counter`에서 관리하는 것과 어떤 차이가 있을까요?

2022-12-14 11:03 UTC, Ubermensch0608 commented on src/components/counter/Counter.jsx
> +  };
`Counter`의 기능을 담당하는 비즈니스 로직은 따로 나누어 관리하는 것이 앱이 확장된다고 했을 때 더 좋을 것이라고 생각했습니다.
가령, `Counter`이외에 `Cart`, `ColorPicker` 등의 기능이 추가된다고 했을 때 모든 비즈니스 로직을 App에서 담당하는 것은 관심사의 분리 취지에 맞지 않겠다고 판단했습니다!
    
그래도 말씀을 듣고 보니 `Counter`에서 온전히 비즈니스 로직만 관리하고 있지는 않은 거 같아서 조금 더 고민이 필요할 수 도 있겠네요. 

`Counter`처럼  확장성을 위해 미리 비즈니스 로직을 분리하는 것이 좋을 지, `App` 처럼 현재 기준에서 생각해야하는지 항상 고민이 되는 부분이네요. 트레이너님은 이 부분에 대해서 어떻게 생각하시나요??

2022-12-15 03:55 UTC, daadaadaah commented on src/components/counter/Counter.jsx
> +  };
만약에 이 앱이 카운터 외의 알람, 스톱워치 기능 등 다양한 기능을 담고 있는 App이라고 요구사항이 주어진다면, 그렇게 할 것 같은데, 우리 과제는 카운터 앱 만들기이므로, 저라면, App에서 비즈니스 로직을 관리한 후 나중에 기능이 확장될 때, 그 요구사항에 맞게 코드를 수정할 것 같습니다!

2022-12-15 03:57 UTC, daadaadaah requested changes
나중에 피드백 강의에서 비즈니스 로직을 어디서 관리하셨느지 한번 살펴보세요!ㅎㅎ

2022-12-15 20:11 UTC, Ubermensch0608 commented on src/components/counter/Counter.jsx
> +  };
그렇군요! 앞으로 어떻게 바뀔 지를 정확히 예측하는 것은 어렵긴 하겠네요.  말씀해주신대로 그 당시 요구사항에 맞추어 작성하는 게 훨씬 효율적일 거 같아요

2022-12-16 02:38 UTC, daadaadaah approved these changes
고생하셨어요!ㅎㅎ다음 과제도 화이팅해봐요!

2022-12-26 11:59 UTC, merged