2주차 과제 - 간단한 카운터앱 만들고 파일 분리하기
CodeSoom/react-week2-assignment-1 pull request #183
Opened 2022-12-13 11:30 UTC by naji0001

이번주도 잘부탁드립니다!

2022-12-14 04:03 UTC, daadaadaah requested changes

2022-12-14 04:03 UTC, daadaadaah commented on src/components/Button.jsx
> +import React from 'react';
리액트17 버전 이후부터는 생략이 가능해요!
사용하시는 리액트 버전을 확인하신 후 적용해보시면 좋을 것 같아요.
참고:
- https://ko.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#whats-different-in-the-new-transform
- https://blog.saeloun.com/2021/07/01/react-17-adds-jsx-runtime-and-jsx-dev-runtime-for-the-new-jsx-transform

2022-12-14 04:03 UTC, daadaadaah commented on src/components/Page.jsx
> +export default function Page({ count, onClick }) {
`Page` 컴포넌트는 현재 App에서 전달 받은 props로 다른 컴포넌트로 전달해주는 역할을 하고 있습니다. 
만약, 지금 `Page` 컴포넌트가 있을 때와 없을 때(=`Page`의 역할을 App에서 하기)에 애플리케이션을 이해하는데 큰 어려움이 있을까요? 추가로 props drilling에 대해 공부해보시면 좋을 것 같아요!

2022-12-14 04:03 UTC, daadaadaah commented on src/index.jsx
> +}
App 컴포넌트로 따로 빼지 않고, index.jsx에 선언하신 이유가 있으신가요?

2022-12-14 11:50 UTC, naji0001 commented on src/index.jsx
> +}
App컴포넌트와 index.jsx의 역할을 이해하지 못해서 그랬던거 같습니다.
App컴포넌트는 상태 관리와 하위 컴포넌트를 조립하는 곳
index.jsx는 서비스의 진입점 외부라이브러리등 유틸들을 import하는 곳 
으로 이해하면될까요?

2022-12-14 11:53 UTC, naji0001 commented on src/components/Page.jsx
> +export default function Page({ count, onClick }) {
`Page` 컴포넌트는 props만 전달할뿐 아무 역할도 하지않아서 제거하였습니다.
props drilling은 todo 과제에서 사용해보겠습니다. 감사합니다.

2022-12-15 03:59 UTC, daadaadaah commented on src/index.jsx
> +}
넵, index 사전적 의미를 생각해보시면 될 것 같아요!

2022-12-15 04:11 UTC, daadaadaah approved these changes
수고하셨습니다! 과제2도 화이팅해봐요!

2022-12-26 11:59 UTC, merged