과제 1 - Counter 앱 만들고 파일 분리하기
CodeSoom/react-week2-assignment-1 pull request #184
Opened 2022-12-13 12:00 UTC by KwangMin-Moon

이번주도 잘 부탁드립니다 트레이너님:)

2022-12-14 08:34 UTC, daadaadaah requested changes

2022-12-14 08:34 UTC, daadaadaah commented on src/button.jsx
> +import React from 'react';
리액트17 버전 이후부터는 생략이 가능해요!
사용하시는 리액트 버전을 확인하신 후 적용해보시면 좋을 것 같아요.
참고:
- https://ko.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#whats-different-in-the-new-transform
- https://blog.saeloun.com/2021/07/01/react-17-adds-jsx-runtime-and-jsx-dev-runtime-for-the-new-jsx-transform

2022-12-14 08:34 UTC, daadaadaah commented on src/counter.jsx
> +  const handleCount = (plus) => {
`plus`라는 표현보다 좀더 의도가 드러나는 표현 없을까요?

2022-12-14 08:34 UTC, daadaadaah commented on src/index.jsx
> +import Counter from './counter';
라이브러리와 local 파일을 구별하기 위해 한줄 띄어주시는게 좋을 것 같아요!

2022-12-14 08:34 UTC, daadaadaah commented on src/page.jsx
> +const Page = ({ count, onClick }) => (
`Page` 컴포넌트는 현재 App에서 전달 받은 props로 다른 컴포넌트로 전달해주는 역할을 하고 있습니다. 
만약, 지금 `Page` 컴포넌트가 있을 때와 없을 때(=`Page`의 역할을 App에서 하기)에 애플리케이션을 이해하는데 큰 어려움이 있을까요? 추가로 props drilling에 대해 공부해보시면 좋을 것 같아요!

2022-12-14 08:34 UTC, daadaadaah commented on src/counter.jsx
> +import Page from './page';
컴포넌트 이름은 대문자로 작성하시는걸 추천 드려요!
참고 : https://ko.reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized

2022-12-14 08:34 UTC, daadaadaah commented on src/counter.jsx
> +  const handleCount = (plus) => {
맥락 구분을 위해 한 줄 띄어줍시다!ㅎㅎ

2022-12-15 11:22 UTC, KwangMin-Moon commented on src/page.jsx
> +const Page = ({ count, onClick }) => (
props를 중간에서 전달하는 역할이 굳이 필요하지는 않을거 같아요
오히려 애플리케이션을 이해하는데 한 단계 더 들어가야해서 더 복잡해진 느낌이 들어요
여기서는 한 단계만 들어가지만 4,5 단계 더 들어가게 되면 더 복잡해질거 같아요
props drilling에 대해 공부했습니다. 왜 redux나 context가 필요한지 조금 더 알게 됐습니다.

2022-12-15 11:22 UTC, KwangMin-Moon commented
코드 리뷰 반영해서 다시 push 했습니다
리뷰 감사드립니다:)

2022-12-16 02:40 UTC, daadaadaah requested changes

2022-12-16 02:40 UTC, daadaadaah commented on src/buttons.jsx
> +      <button key={number} type='button' onClick={() => onClick(btnNumber)}>
`number`는 어디서 받는 변수인가요?

2022-12-16 11:12 UTC, KwangMin-Moon commented
수정해서 다시 push했습니다
이번주도 감사했습니다:)

2022-12-17 05:57 UTC, daadaadaah approved these changes
이번 한주도 고생 많으셨습니다!👏 회고를 통해 한주를 되돌아보고, 피드백강의 보면서 아샬님은 어떻게 하셨는지 한번 관찰해보세요~

2022-12-26 11:59 UTC, merged