Simple counter
CodeSoom/react-week2-assignment-1 pull request #51
Opened 2021-01-25 07:46 UTC by datalater

2주차 1번 과제 제출합니다.

## 과제 해결 방법

1. Counter 컴포넌트를 생성한다. Counter 컴포넌트는 UI를 그려주는 것에만 관심을 갖는다. Counter는 전달받는 state와 핸들러 함수가 어떻게 동작하는지 관심이 없다. state와 핸들러 함수는 App 컴포넌트에서 관리한다.
2. Numbers 컴포넌트를 생성한다. Number 컴포넌트는 UI를 그려주는 것에만 관심을 갖는다. Numbers는 전달받는 핸들러 함수가 어떻게 동작하는지 관심이 없다. 핸들러 함수는 App 컴포넌트에서 관리한다.
3. App 컴포넌트는 Counter와 Numbers가 화면을 어떻게 그리는지 모르겠지만 상태 관리를 한다.

## 궁금한 점

1. TDD를 해보고 싶은데 어떻게 하면 될까요?

## 셀프 리뷰 체크리스트

* [O] UI 반복이 없는가?
* [O]  코드의 의도가 잘 드러나는가?
* [O]  함수 이름에서 코드의 의도가 잘 드러나는가?
* [O]  관심사가 잘 분리되었는가?

## 요청 받은 코드 리뷰 목록

null

## 주간회고

null

2021-01-25 11:17 UTC, datalater commented
리액트 js 문서에 따라 key의 값을 문자열로 바꾼다.

![image](https://user-images.githubusercontent.com/8105528/105699237-60bab700-5f4a-11eb-9aa5-af598457beff.png)

2021-01-25 12:08 UTC, hannut91 commented
`TDD`는 3주차에 배웁니다!

2021-01-25 12:18 UTC, hannut91 requested changes
1등으로 제출해주시다니 ㅎㅎ

2021-01-25 12:18 UTC, hannut91 commented on src/Numbers.jsx
> +export default Numbers;
하나의 파일에는 하나의 컴포넌트만 있는게 좋을 것 같아요

2021-01-25 12:18 UTC, hannut91 commented on src/Numbers.jsx
> +}
`Number`라고 하면 이 컴포넌트의 기능이 단순히 숫자만 보여주는 것 같아요. 하지만 클릭할 수 있으니 누룰 수 있다는 것을 이름으로 드러내는건 어떨까요?

2021-01-25 12:18 UTC, hannut91 commented on src/Numbers.jsx
> +          key={i.toString()}
그냥 숫자를 사용하면 어떤 일이 벌어지나요?

2021-01-25 12:18 UTC, hannut91 commented on src/Numbers.jsx
> +        />
지금은 보여주고 싶은 모습이 단순히 숫자만 있어서 `value`라는 속성으로 값을 전달하고 그 값을 렌더하고 있어요.
지금은 우연히 보여지는 값과 계산에 필요한 값이 완전히 같은데, 만약 다른 경우라면 어떻게 해야 할까요? 예를들어 1, 2, 3, 4, 5가 아니라 `1 만큼 중가시키기` 라던가 사용하는 곳에서 어떻게 보일지 결정할 수 있도록 하려면 어떻게 해야 할까요?

2021-01-25 12:18 UTC, hannut91 commented on src/index.jsx
> +import App from './App';
위에 빈 줄 하나를 추가해서 라이브러리 임포트와 로컬 파일 임포트를 분리하면 좋을 것 같아요

2021-01-25 12:18 UTC, hannut91 commented on src/App.jsx
> +import Counter from './Counter';
여기도 위에 빈 줄 하나를 추가해서 라이브러리 임포트와 로컬 파일 임포트를 구분하면 좋을 것 같아요

2021-01-26 01:32 UTC, datalater commented on src/Numbers.jsx
> +export default Numbers;
분리할까 살짝 고민했었는데 그렇게 하겠습니다!

2021-01-26 01:33 UTC, datalater commented on src/Numbers.jsx
> +}
오호 `NumberButton`으로 바꾸면 클릭할 수 있다는 걸 드러낼 수 있을 것  같아요

2021-01-26 01:42 UTC, datalater commented on src/Numbers.jsx
> +          key={i.toString()}
> [reactjs.org - reconciliation](https://reactjs.org/docs/reconciliation.html#recursing-on-children)

숫자보다 문자열이 나은 이유에 대해 명확히 얘기하는 부분은 없었는데 행간을 파악해보면 다음과 같이 얘기할 수 있을 것 같습니다.

리액트가 key를 사용하는 이유:

* 리액트는 children의 identity를 파악하기 위해서 key를 사용한다. 
* key가 일치하지 않으면 이전 DOM 없던 내용으로 파악하여 새로 그리기 때문에 비효율성이 생긴다.

배열의 index를 key로 사용하면 안 좋은 이유:

* 배열의 index를 key로 사용하면, 배열에 값이 추가되거나 삭제되는 등 index가 변경되는 경우가 발생할 수 있다.
* 이때 배열의 index는 숫자형이므로 배열에 첫번째 요소가 추가되면 이전 index가 모두 1씩 추가되므로 identity 파악에 문제가 된다. 
* 그러나 문자열로 지정하면 배열 첫번째 요소에 값이 새롭게 추가되어도 기존 key값은 문자열이라 영향을 받지 않는다.

결론:

* 리액트의 key는 이전 DOM과 이후 DOM의 차이점을 identify하기 위해 사용되므로 유니크한 값을 사용해야 한다.
* 배열의 index는 숫자형이므로 배열에 요소가 추가되거나 삭제될 경우 index가 계속 변경될 수 있다. 그러나 문자열로 key값을 잡으면 배열이 변경되어도 기존 key값은 영향을 받지 않는다.

2021-01-26 01:49 UTC, datalater commented on src/Numbers.jsx
> +        />
음.. 들어주신 예시가 잘 이해가 안되는데요 😢 

아래 코드처럼 쓰는 게 더 낫다는 걸까요?

```
<Number
  key={i.toString()}
  onClick={() => onClick(value)}
/>
```

2021-01-26 01:51 UTC, datalater commented on src/index.jsx
> +import App from './App';
오 생각하지 못한 포인트네요. 감사합니따!

2021-01-26 01:51 UTC, datalater commented on src/App.jsx
> +import Counter from './Counter';
넵

2021-01-26 01:51 UTC, datalater commented
## 회고 자료를 위한 코드 리뷰 모음

1. 하나의 파일에는 하나의 컴포넌트만 있는 게 좋다. (e.g. Number와 Numbers 분리하기)
2. Number라고 하면 이 컴포넌트의 기능이 단순히 숫자만 보여주는 것 같다. 하지만 클릭할 수 있으니 누를 수 있다는 것을 이름으로 드러내는 게 더 낫다. (e.g. Number => NumberButton)
3. key 값으로 그냥 숫자를 사용하면 어떤 일이 벌어지나?
4. 빈 줄 하나를 추가해서 라이브러리 임포트와 로컬 파일 임포트를 분리한다.

2021-01-26 14:52 UTC, hannut91 commented on src/Numbers.jsx
> +          key={i.toString()}
`index`를 사용하면 문제가 되는 것은 이해했는데, 값을 문자열로 변경하는 이유를 잘 모르겠어요

2021-01-26 14:55 UTC, hannut91 commented on src/Numbers.jsx
> +        />
`1 만큼 증가시키기`라는 이름의 버튼이 있고, 눌렀을 때 1을 증가하도록 만들고 싶어요. 이 기능을 현재 구현된 것으로 구현하려면 어떻게 해야 할까요?

2021-01-26 14:57 UTC, hannut91 approved these changes
좋습니다! ㅎㅎ 제가 말씀드린 것만 한 번 생각해보시면 좋을 것 같아요

2021-01-26 14:57 UTC, hannut91 commented on src/App.jsx
> +        onClick={handleClickCounter}
여기를 `handleClickNumber`로 구현하려면 어떻게 해야 할까요?

2021-01-27 01:18 UTC, datalater commented on src/Numbers.jsx
> +          key={i.toString()}
음 리액트 공식 문서에서 `index.toString()`을 쓰길래 같은 방식으로 쓴 걸로 시작이 됐는데요. 사실 이게 얼마나 영향을 미치는지, 굳이 꼭 문자열을 쓰는 게 큰 이점이 있는지 모르겠지만, 그래도 공식문서에서 굳이 `toString()` 메서드를 실행했는 데에는 이유가 있지 않을까 싶어서 더 조사해봤습니다.

## 결론

(제 생각에 리액트에서 어차피 key값을 문자열로 바꿔야 하는데 미리 해주면) 최적화에 조금 더 도움이 되는 게 아닌가 싶습니다.

## 근거

[stackexchange](https://softwareengineering.stackexchange.com/questions/381268/why-are-react-keys-limited-to-strings):

* HTML 어트리뷰트는 문자열이다. 
* react는 key를 HTML에 쓰고, DOM에서 다시 읽어온다.
* key 값은 문자열로 serialize 되어야 한다.

그래서 index 값을 리액트 코드에서 그대로 숫자로 넣을 때(그림1)와 문자열로 변환해서 넣어준 경우(그림2)를 리액트 개발도구에서 어떻게 나오는지 확인해봤습니다.  그림1과 그림2 모두 HTML로 쓰일 때는 문자열로 변환이 되네요.

그림1
![image](https://user-images.githubusercontent.com/8105528/105927696-dbd5b780-6087-11eb-9df6-fb8a38647ae3.png)

그림2
![image](https://user-images.githubusercontent.com/8105528/105927839-21928000-6088-11eb-8946-7eee83f67b1b.png)

이를 토대로 볼 때 HTML attribute는 string이기 때문에 리액트 공식문서에서도 key 값을 문자열로 변환하기 위해 index 값에 toString 메서드를 쓴 것 같습니다.

2021-01-27 01:35 UTC, datalater commented on src/Numbers.jsx
> +        />
이미 그렇게 구현되어 있지 않나요...?

```jsx
function NumberButton({ value, onClick }) {
  return (
    <button
      type="button"
      onClick={() => onClick(value)}
    >
      {value}만큼 증가시키기
    </button>
  );
}
```

여기서 버튼 이름만 수정하면 들어주신 예시가 구현되는 것 같은데 음.. 뭔가 제가 질문의 의도를 잘 이해하지 못한 것 같습니다😅 더 자세하게 설명해주실 수 있으신가요?

2021-01-27 01:39 UTC, datalater commented on src/App.jsx
> +        onClick={handleClickCounter}
```jsx
const handleClickNumber = (value = 1) => {
   setCount(count + value);
};
```

파라미터 기본값을 쓰면 될 것 같습니다. 어떤가요?

2021-01-27 14:35 UTC, hannut91 commented on src/App.jsx
> +        onClick={handleClickCounter}
오 기본값 좋네요!

2021-01-27 14:36 UTC, hannut91 commented on src/Numbers.jsx
> +        />
```js
function NumberButton({ value, onCheck }) {
  return (
    <button
        type="button"
        onClick={() => onClick(value)}
    >
      {children}
    </button>
  );
```

2021-01-27 14:38 UTC, merged

2021-01-28 01:23 UTC, datalater commented on src/Numbers.jsx
> +        />
아하! 이렇게 되면 NumberButton을 사용하는 곳에서 무엇을 그려줄지 알려주고 NumberButton은 전달받은 내용으로만 UI를 그릴 수 있게 되는군요.

감사합니다!