카운터앱 만들기
CodeSoom/react-week2-assignment-1 pull request #54
Opened 2021-01-25 10:14 UTC by dodoongtak

2021-01-25 12:00 UTC, dodoongtak commented
버튼 컴포넌트에서 onClick을 props에서 꺼내 쓰는 경우에 
추 후 다른 컴포넌트에서 버튼을 사용할 때 문제가 생기지 않을까 생각됩니다. (의존성 문제) 

Q1. 다른 onClick의 성질을 가지는 경우에는 Button을 따로 만들어야 되는것인지요? 아니면 상위 컴포넌트에서 event delgation을 통해 해결해야되는게 맞나요?

폴더 구조를 
component 하위에
```
common/
  Buttons
  Button 
Page/
  page
util/
  Counter
  Reset
```
으로 작성해봤습니다.

Q2. HOC 같은 경우에는 폴더를 따로 만들어서 관리하시나요? 
파일구조를 잡는데 https://reactjs.org/docs/faq-structure.html 공식문서 참고해 작성해 봤습니다.

2021-01-25 13:55 UTC, Kihyun92 requested changes
역시 잘하고 계신 것 같습니다😁 
앞으로 배우게 되겠지만, 고민하신대로 재사용 가능한 컴포넌트를 작성하려고 계속 고민해보시는게 좋네요 👍🏼 


A1. 상황에 따라 다를 것 같아요. 재사용 가능하다면 Button 컴포넌트를 따로 생성하는게 좋을 것 같습니다.

페이지 구조의 경우, src/components가 베이스라서 폴더 네이밍들이 조금 어색해보였어요.

개인적으로는 폴더 구조를 나눈다면 src 아래에
```
commons/
  Buttons
  Button 
Page/
  page
components/
  Counter
  Reset
```
위와 같이 나눌 수 있을 것 같은데, reset의 경우 조금 애매한 것 같기도 하네요.

A2. 프로젝트 크기에 따라서, 그리고 어떤 컴포넌트인지에 따라 다를 것 같아요 ㅎㅎ 저희 팀의 경우엔 주로 `src/common/components/` 에 위치합니다~

2021-01-25 13:55 UTC, Kihyun92 commented on src/components/App.jsx
> +    }
이 부분의 예외처리를 없앨 순 없을까요? 🤔

2021-01-25 13:55 UTC, Kihyun92 commented on src/components/util/Counter.jsx
> +    <Button onClick={() => onClick()}>
```suggestion
    <Button onClick={onClick}>
```

이 경우엔 이렇게만 처리해줘도 좋을 것 같아요

2021-01-25 13:55 UTC, Kihyun92 commented on src/components/util/Reset.jsx
> +function Reset({ onClick }) {
reset도 추가해보셨군요! 좋네요 💯

2021-01-26 00:06 UTC, dodoongtak commented on src/components/App.jsx
> +    }
반영했습니다 :) 

If를 제거해보고 나서
- 왜 If를 무조건 제거 해야될까?
- 언제 If를 제거 해야될까?
- 어떻게 If를 제거 해야될까?

라는 의문이 들어 검색해보며 If 제거 하는 이유에 대해 정리해봤습니다.

첨부링크 : [If를 제거해야되는 진짜 이유](https://www.notion.so/mightytak/If-925d1b8e8eb94c57aea5db100ab8767e)

2021-01-26 00:28 UTC, dodoongtak commented on src/components/util/Counter.jsx
> +    <Button onClick={() => onClick()}>
말씀해주신 코드
```
<Button onClick={onClick}>
```
onClick에 onClick함수를 바로 prop으로 넘기면 Click me가 작동이 되지않습니다. 

() => onClick은 어 되네? onClick은 어 안되네? 라고 넘기기에는... 
놓치고 있는 큰 개념이 어딘가...
bind가 왜 안되는 것이지...ㅎㅎ

원인을 찾아봐서 정리 및 진단 해볼께요!

2021-01-26 12:55 UTC, Kihyun92 commented on src/components/App.jsx
> +    }
와우,, 저희의 의도를 잘 느껴보시고 정리까지 해주신것 같아요! 넘나 좋네요 💯

2021-01-26 13:04 UTC, Kihyun92 requested changes
많은 고민을 해보면서 하시는 것 같아 좋습니다 👍🏼

2021-01-26 13:04 UTC, Kihyun92 commented on src/App.jsx
> +  }
이 함수는 값을 받아서 단순히 이전값에 더해주는 역할인 것 같은데 좀 복잡해보이는군요. 원인이 무엇일까요?

이 함수에서 값이 어떻게될지 예상해서 예외처리를 하는 것 보다, 사용하는 곳에서 값을 다 넘겨준다면 어떨까요?

2021-01-26 13:04 UTC, Kihyun92 commented on src/commons/Button.jsx
> +  const { onClick, children } = props;
이렇게만 처리해도 괜찮을 것 같아요~

```suggestion
function Button({ onClick, children }) {
```

2021-01-27 12:56 UTC, Kihyun92 requested changes
리뷰를 잘 반영해주시는 것 같아요! 마지막 리뷰가 될 것 같네요 👍🏼

2021-01-27 12:56 UTC, Kihyun92 commented on src/App.jsx
> +  }
이것도 괜찮은 방법이네요! 👍🏼 

조금만 개선해보면, 이 경우엔 사용하는 컴포넌트들에서 count 상태를 가지고 있어야하는 불편함이 있는 것 같아요.

```suggestion
  function handleClick(value) {
    setState({
      count: count + value,
    });
  }
```
이렇게 처리해보면 어떤가요? 하위 컴포넌트에 넘기는 매개변수를 하나 줄일 수 있게 될 것 같아요. 어떤가요? 😊

다만 이 경우엔 리셋 컴포넌트에서 사용하기 어려워질 수 있겠네요. 어떻게 해결할 수 있을까요?

2021-01-28 01:48 UTC, dodoongtak commented
## if문 제거 이후 handleClick 함수의 수정 과정 복기

### 수정 1 
```
  function handleClick(value = 1) {
    setState({
      count: count + 1 * (value || -count),
    });
  }
```
리뷰
F1. **이 함수는 값을 받아서 단순히 이전값에 더해주는 역할인 것 같은데 좀 복잡해보이는군요. 원인이 무엇일까요?**
- 원인 : reset을 하기 위해 value 가 0 일시 현재 count 값 만큼 차감할려하기 위한 예외 처리

F2. **이 함수에서 값이 어떻게될지 예상해서 예외처리를 하는 것 보다, 사용하는 곳에서 값을 다 넘겨준다면 어떨까요?**
- 해석 : handleClick에 예외처리로 인한 혼동 야기 -> 값이 어떠냐에 따라 예외를 설정하기에 함수가 출력 결과가 상이함 
-> 퓨어펑션 하지 않음 ( 1주차 리뷰 中 퓨어 펑션에 관한 피드백과 같은 문제 야기)

### 수정 2
```
  function handleClick(value) {
    setState({
      count: value,
    });
  }
```
해결 방법 : value 값이 어떻게 됬든 상관없이 count란 key에 value를 페어링한다 -> 함수가 변동이 없기에 어떤 목적을 가진
함수인지 뚜렷 -> 퓨어함

F1. **이 경우엔 사용하는 컴포넌트들에서 count 상태를 가지고 있어야하는 불편함이 있는 것 같아요.**
- 해석: 피드대로 함수를 퓨어하게 변경해줬지만, count를 하위컴포넌트에 계속 넘겨야되는 부가적인 코드가 발생

### 수정 3
```
  function handleClick(value = 1) {
    setState({
      count: count + value,
    });
  }
```
- 해결 방법 : 수정 1에 기반, 함수를 사용하는 컴포넌트에서 count에 더 해질 value를  직접 넘김. 
※ value를 default값을 1로 설정 -> Counter에서 따로 argument를 보내지 않아도 되는 이점. 1만 증가하기윈한 시 따로 value를 넘길 필요가 없어짐.

F2 -수정 2. **다만 이 경우엔 리셋 컴포넌트에서 사용하기 어려워질 수 있겠네요. 어떻게 해결할 수 있을까요?**

해결 방안 : 
1. count상태를 reset component에 넘김 -> 함수에 **-count**를 매개변수로 넘기며 해결
- reset에서만 count 상태를 가지게 한다. -> count 상태에 의존을 해야되기 떄문에 부가적인 코드 생성은 필연적.

2. 다른 컴포넌트에서 handleClick을 호출 할 떄 count 상태에 의존성이 없게된다. 
※ Counter 컴포넌트에서 count를 매개변수로 갖는건 rendering 할 떄 count의 상태가 필요하기 떄문.
```
// Reset.jsx
  import React from 'react';
  
  import Button from '../commons/Button';
  
  function Reset({ count, onClick }) {
    return (
      <Button onClick={() => onClick(-count)}>Reset</Button>
    );
  }
  
  export default Reset;
```
```
//Counter.jsx
  import React from 'react';
  
  import Button from '../commons/Button';
  
  function Counter({ count, onClick }) {
    return (
      <Button onClick={() => onClick()}>
        Click me
        (
        {count}
        )
      </Button>
    );
  }
  
  export default Counter;
```

2021-01-28 11:58 UTC, Kihyun92 commented on src/components/util/Counter.jsx
> +    <Button onClick={() => onClick()}>
제가 Counter 함수만 보고 리뷰를 드렸던 것 같네요 ㅎㅎ;

혹시 당시에 작동이 되지 않을때 에러나 발생했던 현상이 어떤게 있을까요?

일단 제가 저 당시 커밋 내용 기반으로 테스트를 한번 해봤는데, NAN이 찍히더라구요.
그 이유는 Button 컴포넌트에서 children을 넘겨받은 onClick에 더해주고 있어서 숫자와 문자열이 더해지니 당연히 NAN이 찍히는 것 같아요. 
혹시 다른 부분이 있다면 말씀해주세요~ :)

2021-01-28 12:42 UTC, Kihyun92 commented
> ## if문 제거 이후 handleClick 함수의 수정 과정 복기
> ### 수정 1
> ```
>   function handleClick(value = 1) {
>     setState({
>       count: count + 1 * (value || -count),
>     });
>   }
> ```
> 
> 리뷰
> F1. **이 함수는 값을 받아서 단순히 이전값에 더해주는 역할인 것 같은데 좀 복잡해보이는군요. 원인이 무엇일까요?**
> 
> * 원인 : reset을 하기 위해 value 가 0 일시 현재 count 값 만큼 차감할려하기 위한 예외 처리
> 
> F2. **이 함수에서 값이 어떻게될지 예상해서 예외처리를 하는 것 보다, 사용하는 곳에서 값을 다 넘겨준다면 어떨까요?**
> 
> * 해석 : handleClick에 예외처리로 인한 혼동 야기 -> 값이 어떠냐에 따라 예외를 설정하기에 함수가 출력 결과가 상이함
>   -> 퓨어펑션 하지 않음 ( 1주차 리뷰 中 퓨어 펑션에 관한 피드백과 같은 문제 야기)
> 
> ### 수정 2
> ```
>   function handleClick(value) {
>     setState({
>       count: value,
>     });
>   }
> ```
> 
> 해결 방법 : value 값이 어떻게 됬든 상관없이 count란 key에 value를 페어링한다 -> 함수가 변동이 없기에 어떤 목적을 가진
> 함수인지 뚜렷 -> 퓨어함
> 
> F1. **이 경우엔 사용하는 컴포넌트들에서 count 상태를 가지고 있어야하는 불편함이 있는 것 같아요.**
> 
> * 해석: 피드대로 함수를 퓨어하게 변경해줬지만, count를 하위컴포넌트에 계속 넘겨야되는 부가적인 코드가 발생
> 
> ### 수정 3
> ```
>   function handleClick(value = 1) {
>     setState({
>       count: count + value,
>     });
>   }
> ```
> 
> * 해결 방법 : 수정 1에 기반, 함수를 사용하는 컴포넌트에서 count에 더 해질 value를  직접 넘김.
>   ※ value를 default값을 1로 설정 -> Counter에서 따로 argument를 보내지 않아도 되는 이점. 1만 증가하기윈한 시 따로 value를 넘길 필요가 없어짐.
> 
> F2 -수정 2. **다만 이 경우엔 리셋 컴포넌트에서 사용하기 어려워질 수 있겠네요. 어떻게 해결할 수 있을까요?**
> 
> 해결 방안 :
> 
> 1. count상태를 reset component에 넘김 -> 함수에 **-count**를 매개변수로 넘기며 해결
> 
> * reset에서만 count 상태를 가지게 한다. -> count 상태에 의존을 해야되기 떄문에 부가적인 코드 생성은 필연적.
> 
> 1. 다른 컴포넌트에서 handleClick을 호출 할 떄 count 상태에 의존성이 없게된다.
>    ※ Counter 컴포넌트에서 count를 매개변수로 갖는건 rendering 할 떄 count의 상태가 필요하기 떄문.
> 
> ```
> // Reset.jsx
>   import React from 'react';
>   
>   import Button from '../commons/Button';
>   
>   function Reset({ count, onClick }) {
>     return (
>       <Button onClick={() => onClick(-count)}>Reset</Button>
>     );
>   }
>   
>   export default Reset;
> ```
> 
> ```
> //Counter.jsx
>   import React from 'react';
>   
>   import Button from '../commons/Button';
>   
>   function Counter({ count, onClick }) {
>     return (
>       <Button onClick={() => onClick()}>
>         Click me
>         (
>         {count}
>         )
>       </Button>
>     );
>   }
>   
>   export default Counter;
> ```

리뷰를 드리는 내용을 하나하나 이해하시면서 진행하고 어떻게 고민하셨는지 남겨주셔서 감사합니다 💯 

`-count` 로 처리하는 방식도 좋네요!

저는 단순하게 App 컴포넌트에 리셋 함수를 새로 만들어도 좋겠다고 생각했어요. 😁

2021-01-28 12:49 UTC, Kihyun92 commented on src/commons/Button.jsx
> +      onClick={() => onClick(children)}
앞에서 고민하신 문제의 원인은 이곳 일 수 있을 것 같아요.

버튼 컴포넌트에서는 onClick으로 어떤 값이 넘어오던, 그냥 클릭이 되면 onClick 함수를 실행해주는 겁니다.
```suggestion
      onClick={onClick}
```

그리고 사용하는 쪽에서 어떤 클릭이 있을지를 넘겨주는 방식인거죠.
```javascript
// Counter.jsx -> 여기선 클릭시 1씩 더해줄 것이기 때문에 인자로 1을 넘겨줍니다.
<Button onClick={() => onClick(1)}>
```

Button 컴포넌트에서 children을 넘기다보니 버튼 컴포넌트를 사용하는 쪽에서 어떤식으로 사용할지 모르기 때문에, 우리의 의도와 다른 영향, 사이드 이펙트가 발생할 수 있을 것 같아요.

2021-01-29 04:55 UTC, dodoongtak commented on src/commons/Button.jsx
> +      onClick={() => onClick(children)}
부수효과를 줄이기 위해 onClick(children)이 아닌 count를 받아 onClick(count)가 될 수 있도록 변경 진행해봤습니다. 🙌

2021-01-29 05:04 UTC, dodoongtak commented
## 과제 2-1 복기
1. if 문 또는 value를 mutate 시킬 수 있는 함수작성으로 퓨어 함수 파괴 <- 과제 1 리뷰에서 언급 됐던 부분
- https://github.com/CodeSoom/react-week2-assignment-1/pull/54#issuecomment-769027300
2. 하위컴포넌트와 상위 컴포넌트 간의 props 전달 방식의 오류
- https://github.com/CodeSoom/react-week2-assignment-1/pull/54#discussion_r566068548

처음과 마지막 코드를 비교해보면 개별 코드가 특정한 로직을 실행시켜 변동이 없는 아웃풋을 내는 코드로 작동할 수 있게끔 변경되었습니다.

상위에서 고쳐도 전체적으로 업데이트 되기떄문에, 유지보수에 있어 불필요한 처리가 줄어들게 된게 제일 큰 차이로 보여집니다!

2021-01-29 12:58 UTC, Kihyun92 approved these changes

2021-01-31 14:27 UTC, merged