Simple CounterApp Implement
CodeSoom/react-week2-assignment-1 pull request #62
Opened 2021-01-25 17:25 UTC by SangHoonly

컴포넌트들을 나눠서 구현했습니다. 현재 실행되는 것을 확인했고요.
이 과제에서는 eslint가 자꾸 말을 안듣네요. eslint가 고치라는 대로 고치고 저장버튼(command + S)을 누르면 고치기 전으로 되돌아가면서 다시 eslint의 빨간줄이 뜹니다. 어디서부터 잘못된 것일까요??
![images](https://user-images.githubusercontent.com/54464320/105741442-a775d480-5f7d-11eb-85ef-7ed98fc0c799.jpeg)

2021-01-25 18:02 UTC, SangHoonly commented
자동 포매팅 기능을 끄니 되긴 되네요...

2021-01-25 19:36 UTC, SangHoonly commented
다른 분들의 코드를 보고 느낀 점이 있어 수정했습니다!

2021-01-26 13:08 UTC, Kihyun92 commented
![image](https://user-images.githubusercontent.com/35797540/105848739-c5e1db80-6022-11eb-93ed-d09bcc0b5e97.png)

현재 풀 리퀘스트의 타겟 브랜치가 잘못 된 것 같아요!  상단에 Edit을 눌러 CodeSoom:<user-github-id>로 수정해주세요.
항상 PR올리시고 확인해주세요~

2021-01-26 13:19 UTC, Kihyun92 requested changes
좋습니다. 잘 진행해보고 계신듯 하네요 ㅎㅎ

다른 분들의 코드를 보고 하는건 문제가 없습니다만, 말씀하신대로 어떤 방향점을 느꼈다던지, 그런 부분을 공유해주시면 리뷰할때 도움이 될뿐아니라 본인에게도 도움이 될 것 같아요~ 👍🏼

2021-01-26 13:19 UTC, Kihyun92 commented on package.json
> +}
파일 마지막에 공백 라인 하나를 추가해 주세요. 파일이 `}`와 같이 공백이 아닌 문자로 끝나게 되면 github에서 다음과 같이 경고가 나옵니다.
![image](https://user-images.githubusercontent.com/35797540/105849089-4274ba00-6023-11eb-983e-ee102878e8c5.png)

2021-01-26 13:19 UTC, Kihyun92 commented on src/Components/Home.jsx
> +function Home() {
컴포넌트 네이밍을 Home이라고 한 이유가 있을까요? 단순히 Page라 하는건 어떨까요 ㅎㅎ

딱히 정답은 없지만, 이런 컴포넌트는 하위 컴포넌트들을 모아서 처리해주는 역할이기 때문에 개인적으론 XXXPage가 조금 더 익숙한 느낌입니다. 본인의 의견에 맞게 적용해주세요~

2021-01-26 13:19 UTC, Kihyun92 commented on src/index.jsx
> +}
index.jsx는 진입점으로 컴포넌트는 아닙니다. App은 컴포넌트입니다:)

2021-01-26 13:19 UTC, Kihyun92 commented on src/Components/Home.jsx
> +      <Counter count={count} onClick={setCount} />
click 했을때에대한 처리를 위해서 setCount를 넘기셨군요 ㅎㅎ 이렇게되면 넘겨받은 자식 컴포넌트에서 setCount를 가지고 이런저런 처리를 하게 됩니다. 어떤 사이드 이펙트가 발생할지 모르겠네요.

이 경우에는 따로 핸들러 함수를 자식 컴포넌트에 제공하는건 어떨까요?

2021-01-26 15:26 UTC, SangHoonly commented on package.json
> +}
넵 추가하겠습니다!

2021-01-26 15:28 UTC, SangHoonly commented on src/Components/Home.jsx
> +function Home() {
메인 홈이란 생각으로 Home이라 이름 붙였습니다..ㅎㅎ 컴포넌트의 역할에 따라 Page라고 쓰겠습니다!

2021-01-26 15:55 UTC, SangHoonly commented on src/Components/Home.jsx
> +      <Counter count={count} onClick={setCount} />
알겠습니다!

2021-01-26 16:00 UTC, SangHoonly commented
알려주신 사항을 바탕으로 코드를 개선하였습니다.
수정사항)
1. package.json 맨 끝 공백 라인 추가
2. 컴포넌트 네이밍 수정) Home -> Page
3. index.jsx의 App함수 삭제
4. click했을 시 핸들러 함수 추가

2021-01-27 13:03 UTC, Kihyun92 requested changes

2021-01-27 13:03 UTC, Kihyun92 commented on src/index.jsx
> +ReactDOM.render(<Page />, document.getElementById('app'));
앗 제가 설명이 조금 부족했던 것 같습니다! 리뷰를 잘 반영해 주셨는데, 제 의도는 index에서 App 컴포넌트를 import하는건 맞지만, 그 내부 처리를 어떻게 가져갈지에 대해서 말씀을 드리고 싶었던 것 같아요.

현재 Page 컴포넌트에서 하는 역할을 조금 분리해보면 어떨까요? 관심사를 분리하는거죠.

Page 컴포넌트의 역할은 무엇인가요? 그려지는 부분을 관리해주는 역할이죠.
App에서는 사용되는 상태값들을 관리하고 어떻게 사용할지는 Page 컴포넌트에 위임하는 방식이 될 것 같아요 🤔  어떤가요?

2021-01-27 13:08 UTC, Kihyun92 commented
추가로 커밋 메시지가 조금 단조로운 것 같아요 😂

fix 대신 PR에 커맨트 달아주신 내용을 커밋 메시지로 적는건 어떨까요? ㅎㅎ 동료들이 당시의 PR을 찾아보기보다 커밋 메시지만 보고도 어떤 작업을 했는지 쉽게 파악할 수 있게요.

2021-01-27 15:12 UTC, SangHoonly commented on src/index.jsx
> +ReactDOM.render(<Page />, document.getElementById('app'));
아하 감 잡았습니다ㅎㅎㅎ 감사합니다!!

2021-01-27 15:28 UTC, SangHoonly commented
얘기해주신 사항을 반영하여 커밋 메시지 작성하겠습니다!!

2021-01-28 13:49 UTC, Kihyun92 requested changes
https://github.com/CodeSoom/react-week2-assignment-1/pull/62#discussion_r564501243

제가 이 부분의 설명이 조금 부족했던 것 같아요 ㅎㅎ

setCount를 자식 컴포넌트로 넘겨서 사용하는 컴포넌트에서 핸들러함수를 구현해보신 것 같아요.

이렇게 처리될 경우에는 setCount 함수가 여기저기에서 사용되어 count 값이 어디서 변경될지 예측이 안될 것 같아요.

만약 상태를 관리하는 App에서 count 값을 변경할 수 있도록 핸들러 함수들을 만들어서 자식 컴포넌트에 제공하면 어떨까요? 
우리가 제공하는 핸들러 함수만을 이용해서 자식 컴포넌트들은 count를 변경하게 되겠죠. 우리가 의도한대로요.

우리가 의도한 영향인지 아닌지 이게 중요한 것 같아요. 우리가 의도하지 않은 영향을 사이드 이펙트라고도 합니다.

2021-01-28 13:49 UTC, Kihyun92 commented on src/Components/Page.jsx
> +  }
count 상태를 변경하는 함수를 만들어보셨네요~

다만 page컴포넌트에서 이런 상태에 대한 변경 처리를 해주는게 맞나요? page 컴포넌트가 이 부분을 알아야할까요?

상태를 처리해주는 상위 컴포넌트로 이 역할을 위임하는건 어떤가요? Page 컴포넌트에서는 화면에 노출할 부분만 관심있도록요.

2021-01-28 13:49 UTC, Kihyun92 commented on src/Components/Buttons.jsx
> +        </button>
이 영역 또한 컴포넌트로 분리하면 어떤가요?

2021-01-28 17:04 UTC, SangHoonly commented on src/Components/Page.jsx
> +  }
아하 App컴포넌트에서 핸들러 함수들을 만들어서 하위 컴포넌트들에게 전해주면, 하위 컴포넌트들은 단지 그걸로 보여주는 기능만 하는 식으로 코드를 작성하라는 거군요!! 이런 식으로 작성해야 사이드 이펙트가 발생하지 않는다는 것이고요.

2021-01-28 18:23 UTC, SangHoonly commented
리뷰해주신 내용 참고하여 코드를 수정하였습니다.
App 컴포넌트에서 핸들링 함수들을 정의 후 하위 컴포넌트에게 전달하는 방식으로 코드를 수정하였고,
모든 숫자 버튼 기능을 모아 놓은 컴포넌트를, 버튼 리스트의 컴포넌트와 버튼 그 자체의 컴포넌트로 분리하였습니다.

2021-01-29 13:19 UTC, Kihyun92 requested changes
리뷰를 잘 이해하면서 반영해주신 것 같습니다!

핸들러 함수들의 네이밍에 관한 문서 한번 봐보시면 좋을 것 같아요~
- https://medium.com/javascript-in-plain-english/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364

2021-01-29 13:19 UTC, Kihyun92 commented on src/Components/NumberButton.jsx
> +    <button name={number} type="button" onClick={onClick}>
App 컴포넌트에서 buttonClick함수에서 event.target.name 값을 사용야하는 이유가 있을까요? 이렇게 숫자만 넘기도록 처리하는건 어떤가요?

```suggestion
    <button type="button" onClick={() => onClick(number)}>
```

2021-01-29 15:05 UTC, SangHoonly commented
핸들러 함수 네이밍의 규칙들이 있었군요... 좋은 정보 감사합니다!!
숫자를 넘겨 사용하는 방식은 미처 생각하지 못했는데, 좋은 부분 지적해주셔서 감사합니다~ㅎㅎ

2021-01-30 13:05 UTC, Kihyun92 approved these changes
좋습니다. 이번 과제를 하면서 정말 많은 고민을 해보신 것 같아요😁

처음 작성한 코드와 마지막 코드를 비교하면서 어떤 변화가 일어났는지 보시면 좋을 것 같아요.

그리고 과제 풀이 영상은 꼭 보시면 좋겠습니다~

2021-01-31 15:01 UTC, merged