Simple counter app
CodeSoom/react-week2-assignment-1 pull request #63
Opened 2021-01-26 09:42 UTC by ParkYoungHoon

숫자 1 ~ 5 버튼 누르면 해당 숫자만큼 N씩 증가 되도록 구현

2021-01-26 14:16 UTC, ParkYoungHoon commented
감사합니다! 말씀 해주신 부분 고려해서 추가 작업 후 올리겠습니다.
커밋 메시지도 개선해서 작성하겠습니다.

2021-01-27 13:23 UTC, Kihyun92 requested changes
리뷰를 잘 반영해주시는것 같아요! 잘 진행하고 계신 것 같아 좋습니다 👍🏼

2021-01-27 13:23 UTC, Kihyun92 commented on src/button.jsx
> +}
파일 마지막에 공백 라인 하나를 추가해 주세요. 파일이 }와 같이 공백이 아닌 문자로 끝나게 되면 github에서 다음과 같이 경고가 나옵니다.
![image](https://user-images.githubusercontent.com/35797540/105996358-8d5b0400-60ed-11eb-8d8a-8074307677ec.png)

다른 부분들도 확인해서 수정해주세요 :)

2021-01-27 13:23 UTC, Kihyun92 commented on src/index.jsx
> +    }
비슷한 역할을 하고 있는 함수들 같네요~ 하나로 합칠 순 없을까요? 🤔

2021-01-27 13:23 UTC, Kihyun92 commented on src/index.jsx
> +}
index.jsx는 진입점으로 컴포넌트는 아니지만, App은 컴포넌트입니다. 따로 분리하는게 좋겠네요ㅎㅎ

2021-01-27 13:23 UTC, Kihyun92 commented on src/index.jsx
> +            <NumberButtons onClick={numClick} />
App컴포넌트에서 이 부분들을 관리하고 있을 필요가 있을까요?

관심사 측면에서 App과 Page 컴포넌트의 각각의 역할이 무엇인가요?

2021-01-27 13:23 UTC, Kihyun92 commented on src/numberButtons.jsx
> +            {[1, 2, 3, 4, 5].map(i => <button type='button' key={i} onClick={() => onClick(i)}>{i}</button>)}
map 내부의 버튼 또한 분리 가능하지 않을까요?

2021-01-28 12:00 UTC, ParkYoungHoon commented on src/index.jsx
> +            <NumberButtons onClick={numClick} />
App 컴포넌트는 상태를 바꿔주는 역할을 하고
Page 컴포넌트는 결과를 보여주는 역할을 합니다.

2021-01-28 12:32 UTC, Kihyun92 requested changes
리뷰 드린 내용을 고민해보시는 것 같아 너무 좋습니다 👍🏼 

진행하시다가 의논이 필요하다면 언제든 커멘트/DM 주세요~

2021-01-28 12:32 UTC, Kihyun92 commented on src/app.jsx
> +    function numClick(i){
일반적으로 함수는 `handleClick~~` 와 같이 네이밍을 합니다.

props로 받는 경우엔 `onClick~~` 처럼 하구요.

참고
- https://medium.com/javascript-in-plain-english/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364

2021-01-28 12:32 UTC, Kihyun92 commented on src/app.jsx
> +            count: count + i,
추가로 단순히 `i` 라는 네이밍보다는 우리가 넘겨서 더해주는 값이라는 의도가 나타날 수 있는 `number` 혹은 `increase`와 같은 네이밍은 어떤가요?

2021-01-28 12:32 UTC, Kihyun92 commented on src/app.jsx
> +        <div>
이 `div` 태그는 꼭 필요하지 않으면 없어도 될 것 같네요~

2021-01-29 13:27 UTC, Kihyun92 requested changes
이 부분만 수정해주시면 될 것 같아요~

2021-01-29 13:27 UTC, Kihyun92 commented on src/numberButtons.jsx
> +
하나의 파일엔 하나의 컴포넌트만 존재해야합니다. 이 부분은 따로 파일로 분리해주는게 좋겠네요~

2021-01-29 13:51 UTC, ParkYoungHoon commented on src/numberButtons.jsx
> +
ShareButtons Component 별도 파일로 분리시켰습니다!

2021-01-30 13:04 UTC, Kihyun92 approved these changes
좋습니다. 이번 과제를 하면서 정말 많은 고민을 해보신 것 같아요😁

처음 작성한 코드와 마지막 코드를 비교하면서 어떤 변화가 일어났는지 보시면 좋을 것 같아요.

그리고 과제 풀이 영상은 꼭 보시면 좋겠습니다~

2021-01-31 15:10 UTC, merged