make counter app
CodeSoom/react-week2-assignment-1 pull request #64
Opened 2021-01-26 10:59 UTC by yoonhe

2021-01-26 13:29 UTC, Kihyun92 commented
풀 리퀘스트에 내용도 채워주시면 좋을 것 같아요~ 몇 단어만 쓰셔도 좋지만, 작업 내용이나 고민하셨던 부분이라던지 동료들이 이 PR이 어떤 내용을 담고 있는지 설명해주시면 좋습니다 😁

2021-01-26 13:38 UTC, Kihyun92 requested changes
이번 과제의 의도인 관심사 분리에 대해서 많이 고민해 보신것 같아요~ 잘 진행하고 계신 것 같습니다 👍🏼

2021-01-26 13:38 UTC, Kihyun92 commented on src/App.jsx
> +function App() {
App은 최상위 컴포넌트로 UI를 선언한 부분이 단순하게 읽히는 게 좋은데 지금은 구체적인 구현이 많이 노출된 상황입니다.
어떻게 개선할 수 있을까요?

App은 최상위 부모이기 때문에 App에서 렌더되는 컴포넌트는 조금 추상적이어도 좋습니다.
예를 들면 XXXPage죠. 그 안에 어떤 컴포넌트가 구성되어 있는진 관심사가 아니도록 해보세요.

2021-01-26 13:38 UTC, Kihyun92 commented on src/App.jsx
> +import Counter from './Counter';
리액트 라이브러리 임포트와 로컬 컴포넌트 임포트를 구분하기 위해한 줄 공백을 주시면 좋을 것 같습니다! 지금은 모듈이 별로 없지만, 모듈 간에도 역할이 있고, 분리를 해두는 습관을 두면 좋을 것 같아요

다른 파일들도 적용해주세요~

2021-01-26 13:38 UTC, Kihyun92 commented on src/App.jsx
> +  }
주로 핸들러 함수를 선언할땐 `handleClick~~`와 같이 네이밍을 합니다. 

그리고 현재 컴포넌트에서 이게 버튼을 클릭해서 발생한건지는 관심 밖일 것 같아요. 단순히 `handleClick`은 어떨까요?

마찬가지 관점에서 prevCount보다 `count`는 어떨까요?

마지막으로 아래 `onClickNumberButton` 함수와 비슷한 역할을 하는 것 같은데 하나로 합칠 순 없을까요? App 컴포넌트 입장에서 count라는 상태값에 1을 더하던 number를 더하던 뭔가를 더한다는건 같은 것 같아요.

2021-01-26 13:38 UTC, Kihyun92 commented on src/Button.jsx
> +  return <button type="button" onClick={onClick}>{children}</button>;
```suggestion
  return (
    <button type="button" onClick={onClick}>
      {children}
    </button>
  );
```

가독성 측면에서 줄바꿈 처리를 해주는건 어떨까요?

2021-01-26 15:00 UTC, yoonhe commented
관심사의 분리 개념이 좀 헷깔리는데요.. 아래와같이 이해하고있는 내용을 정리해보았는데 
제가 이해를 하고있는게 맞을까요?.. ㅜㅜ

화면에 그려주는 내용들만 가지고 있는 컴포넌트(UI 로직)
- props들이 무엇인지는 모름(관심사가 아님)
- 관심사 : 받은 `props` 를 화면에 어떻게 보여줄지?
- 화면에 어떻게 보여줄지를 선언

상태를 관리하는 컴포넌트(비지니스 로직)
- 관심사 : 상태를 어떻게 관리할지, 상태가 어떻게 변할지
- 컴포넌트가 어떻게 그려지는 관심사가 아님

2021-01-27 04:29 UTC, yoonhe commented on src/App.jsx
> +  }
```js
const [count, setCount] = useState(0);

  function handleClick(number = 1) {
    // eslint-disable-next-line no-shadow
    setCount((count) => count + number);
  }
```

`prevCount`를 `count`로 변경하니 아래와같은 에러가 발생하는데요
![image](https://user-images.githubusercontent.com/53102889/105943014-b35bb680-60a3-11eb-956c-337cacefdd7e.png)

` // eslint-disable-next-line no-shadow`  주석을 이용해도 괜찮은가요??

2021-01-27 04:31 UTC, yoonhe commented on src/App.jsx
> +function App() {
아래처럼 수정했습니다. `App` 컴포넌트는 상태를 관리하고 넘겨주는 것이 관심사가 되고 `Page` 컴포넌트가 무엇을 렌더링하는지에 대해서는 관심사가 아니도록 표현했는데 제가 알맞게 표현한게 맞을까요?

```js
function App() {
  const [count, setCount] = useState(0);

  function handleClick(number = 1) {
    setCount((count) => count + number);
  }

  return (
    <Page count={count} onClick={handleClick} />
  );
}
```

2021-01-27 04:37 UTC, yoonhe commented on src/Button.jsx
> +  return <button type="button" onClick={onClick}>{children}</button>;
수정했습니다!

2021-01-27 10:29 UTC, yoonhe commented
숫자 배열을 버튼 컴포넌트로 렌더링하다 보니 궁금한점이 생겼습니다.
현재 카운터 컴포넌트에서는 아래와같이 숫자 배열을 `map`을 통해 버튼 컴포넌트로 변환해주고 있는데요
```js
{[1, 2, 3, 4, 5].map((number) => (
        <Button
          key={number}
          onClick={
            () => onClick(number)
          }
        >
          {number}
        </Button>
      ))}
```
만약에 각 버튼마다 `onClick` 이벤트가 다르다면 그때는 아래와같이 배열에 onClickd 이벤트를 key,  value로 추가해주나요?? 

```js
const buttons = [{id: 1, text: "button1", onClick: () => 'button1 이벤트'}, {id: 2, text: "button2", onClick: () => 'button2 이벤트'}]]

function Buttons({ onClick }) {
  return (
    <p>
      {buttons.map((number) => (
        <Button
          key={number.id}
          onClick={
            number.onClick
          }
        >
          {number.text}
        </Button>
      ))}
    </p>
  );
}
```

2021-01-27 13:07 UTC, Kihyun92 requested changes
좋아요~ 과제의 의도를 잘 파악하고 계신 것 같아요 👍🏼

2021-01-27 13:07 UTC, Kihyun92 commented on src/App.jsx
> +function App() {
좋습니다!

2021-01-27 13:07 UTC, Kihyun92 commented on src/App.jsx
> +    setCount((count) => count + number);
![image](https://user-images.githubusercontent.com/35797540/105995017-bbd7df80-60eb-11eb-8282-51f844f16111.png)
에러가 발생하고 있네요. 어떻게 해결할 수 있을까요?

2021-01-27 13:07 UTC, Kihyun92 commented on src/Page.jsx
> +import Counter from './Counter';
리액트 라이브러리 임포트와 로컬 컴포넌트 임포트를 구분하기 위해한 줄 공백을 주시면 좋을 것 같습니다! 지금은 모듈이 별로 없지만, 모듈 간에도 역할이 있고, 분리를 해두는 습관을 두면 좋을 것 같아요

다른 파일들도 확인해주세요~

2021-01-27 13:11 UTC, yoonhe commented on src/App.jsx
> +    setCount((count) => count + number);
count 변수를 이미 사용해서 그런것 같은데 useState에서 사용하는 count 변수 네이밍을 바꿔주는게 좋을까요?..

2021-01-27 13:12 UTC, Kihyun92 commented on src/App.jsx
> +  }
아니요! 이 부분은 다른 방식으로 해결할 수 있을 것 같아요. 

저 에러가 발생하는 원인을 고민해보시면 좋겠습니다. 상위 스코프에 count가 이미 선언되어 있다.
`setCount(count + number);`와 같이 처리를 하지 못하는 이유가 있나요?

2021-01-27 13:13 UTC, Kihyun92 commented
> 관심사의 분리 개념이 좀 헷깔리는데요.. 아래와같이 이해하고있는 내용을 정리해보았는데
> 제가 이해를 하고있는게 맞을까요?.. ㅜㅜ
> 
> 화면에 그려주는 내용들만 가지고 있는 컴포넌트(UI 로직)
> 
> * props들이 무엇인지는 알필요가 없음, 그냥 받아서 그려주기만 하면 됨(관심사가 아님)
> * 관심사 : 받은 `props` 를 화면에 어떻게 보여줄지?
> * 화면에 어떻게 보여줄지를 선언
> 
> 상태를 관리하는 컴포넌트(비지니스 로직)
> 
> * 관심사 : 상태를 어떻게 관리할지, 상태가 어떻게 변할지
> * 컴포넌트가 어떻게 그려지는 관심사가 아님
> * 그저 컴포넌트에 상태를 넘겨주기만 하면됨

잘 이해하신 것 같습니다! 이렇게 분리함으로써 얻는 장단점에 대해서도 고민해보시면 더 좋을 것 같아요 😊

2021-01-27 13:16 UTC, Kihyun92 commented
> 숫자 배열을 버튼 컴포넌트로 렌더링하다 보니 궁금한점이 생겼습니다.
> 현재 카운터 컴포넌트에서는 아래와같이 숫자 배열을 `map`을 통해 버튼 컴포넌트로 변환해주고 있는데요
> 
> ```js
> {[1, 2, 3, 4, 5].map((number) => (
>         <Button
>           key={number}
>           onClick={
>             () => onClick(number)
>           }
>         >
>           {number}
>         </Button>
>       ))}
> ```
> 
> 만약에 각 버튼마다 `onClick` 이벤트가 다르다면 그때는 아래와같이 배열에 onClickd 이벤트를 key, value로 추가해주나요??
> 
> ```js
> const buttons = [
>   {id: 1, text: "button1", onClick: () => 'button1 이벤트'}, 
>   {id: 2, text: "button2", onClick: () => 'button2 이벤트'}
> ];
> 
> function Buttons({ onClick }) {
>   return (
>     <p>
>       {buttons.map((number) => (
>         <Button
>           key={number.id}
>           onClick={
>             number.onClick
>           }
>         >
>           {number.text}
>         </Button>
>       ))}
>     </p>
>   );
> }
> ```
> 
> `onClick` 뿐만 아니라 `children`도 상황에 따라 다른 `react component`를 전달해주고 싶을때 아래와같이 전달해도 되나요??
> 
> ```js
> const buttons = [
>   {id: 1, text: "button1", child: <TestChildOne />, onClick: () => 'button1 이벤트'}, 
>   {id: 2, text: "button2", child: <TestChildTwo />, onClick: () => 'button2 이벤트'}
> ]
> ```

조금 다를 순 있지만 근본적으론 말씀하신대로 사용하기도 합니다.ㅎㅎ
하지만 조금 복잡해질 수 있죠. 분리가 가능하다면 분리하는것도 방법입니다.

2021-01-27 13:17 UTC, yoonhe commented on src/App.jsx
> +  }
상위에 `const`로 `count` 변수가 선언되어서  `setCount((count) => count + number)` 에서 `count`를 중복하여 사용하기때문에 에러가 나는게 맞을까요?.. 그렇다면 `setCount`의 변수 네이밍을 countState 이런식으로 바꿔주면 될까요??

2021-01-28 03:45 UTC, yoonhe commented
다른분의 코드리뷰를 구경하다 궁금한점이 생겼습니다.

![image](https://user-images.githubusercontent.com/53102889/106086877-4d843300-6166-11eb-862e-f29afb945122.png)

`props`로 `setCount` 자체를 넘기게 되면 `자식 컴포넌트`에서 이를 가지고 이런저런 처리를 하게 된다고 하셨는데, 넘겨받은 `setState`로 여러가지 처리를 하면 왜 안되는건가요???

`props`로 `setCount` 자체를 넘기는 것과 `handleClick` 함수에 `setCount(count + valut)`를 넣어서 전달하는 것의 차이가 궁금합니다..!

2021-01-28 07:16 UTC, yoonhe commented
질문이 갑자기 많이 생기네요.. 저 `git` 관련하여 질문할게 있습니다.
현재 https://github.com/CodeSoom/git-training 해당 링크를 참고하여 과제를 하고있는데요

제 작업순서는 아래와같습니다.
1. git clone [repo]
2. git remote add upstream [코드숨 repo]
3. git fetch upstream main
4. git switch -c develop upstrea/main

그런데 여기서 궁금한거는 위와같이 하게되면 새로 만든 `develop` 브랜치에는 최신 브랜치 내용이 반영이 되지만
제 로컬의 `main` 브랜치는 최신 브랜치 내용이 반영 되지 않는데  `main` 브랜치는 최신 브랜치 내용으로 업데이트를 시켜줄 필요가 없는건가요??

2021-01-28 08:19 UTC, yoonhe commented on src/App.jsx
> +  }
`setCount`에 `count`를 제거하니 문제가 해결되었습니다! 

````js
const [count, setCount] = useState(0);

  function handleClick(number = 1) {
    setCount(() => count + number);
  }
```

2021-01-28 12:06 UTC, yoonhe commented
> 잘 이해하신 것 같습니다! 이렇게 분리함으로써 얻는 장단점에 대해서도 고민해보시면 더 좋을 것 같아요

관심사를 분리함으로써 얻는 장단점에 대해서 구글링 해보았습니다.
1.  컴포넌트의 재사용성을 높일 수 있다.
2.  버그를 추적하기가 수월해진다.
3.  상태와 이벤트 핸들러가 어느 JSX 부분에 사용되는지 추적하기가 쉬워진다?

또 장점이 더 있을까요???

2021-01-28 13:16 UTC, Kihyun92 commented
> 다른분의 코드리뷰를 구경하다 궁금한점이 생겼습니다.
> 
> ![image](https://user-images.githubusercontent.com/53102889/106086877-4d843300-6166-11eb-862e-f29afb945122.png)
> 
> `props`로 `setCount` 자체를 넘기게 되면 `자식 컴포넌트`에서 이를 가지고 이런저런 처리를 하게 된다고 하셨는데, 넘겨받은 `setState`로 여러가지 처리를 하면 왜 안되는건가요???
> 
> `props`로 `setCount` 자체를 넘기는 것과 `handleClick` 함수에 `setCount(count + value)`를 넣어서 전달하는 것의 차이가 궁금합니다..!

물론 setCount를 넘겨서 count에 대한 이런 저런 처리를 해도 됩니다. 안되진 않아요.
하지만, 이 경우에는 count는 상태 값이 어디서 변경하는지 모르고, setCount에 어떤 값을 어떻게 넘겨서 count를 변경시키는지 예측이 안됩니다.
반면에 count 값을 변경할 수 있도록 핸들러 함수들을 만들어서 자식 컴포넌트에 제공하면 어떨까요? 우리가 제공하는 핸들러 함수만을 이용해서 자식 컴포넌트들은 count를 변경하게 되겠죠. 우리가 의도한대로요.

우리가 의도한 영향인지 아닌지 이게 중요한 것 같아요. 우리가 의도하지 않은 영향을 사이드 이펙트라고도 하죠.

2021-01-28 13:20 UTC, yoonhe commented
> 계속 고민해보면서 하시는 모습이 좋네요 💯
이런 부분들은 슬랙 채널에서 동료들과 함께 고민해보는 것도 좋을 것 같습니다 :)

기현님 감사합니다. 슬랙에 한번 올려보았는데 좋은 답변들을 많이 받았습니다 ㅎㅎㅎㅎㅎㅎㅎ

2021-01-28 13:33 UTC, Kihyun92 commented
> 질문이 갑자기 많이 생기네요.. `git` 관련하여 질문할게 있습니다.
> 현재 https://github.com/CodeSoom/git-training 해당 링크를 참고하여 과제를 하고있는데요
> 
> 제 작업순서는 아래와같습니다.
> 
> 1. git clone [repo]
> 2. git remote add upstream [코드숨 repo]
> 3. git fetch upstream main
> 4. git switch -c develop upstrea/main
> 
> 그런데 여기서 궁금한거는 위와같이 하게되면 새로 만든 `develop` 브랜치에는 최신 브랜치 내용이 반영이 되지만
> 제 로컬의 `main` 브랜치는 최신 브랜치 내용이 반영 되지 않는데 `main` 브랜치는 최신 브랜치 내용으로 업데이트를 시켜줄 필요가 없는건가요??

upstream/main이 변경되면 origin/main에 반영해줘도 좋지만, origin/main은 굳이 최신으로 업데이트 할 필요가 없습니다.
그 이유에 대해 생각해보면 우리는 main 브랜치에서 분리한 origin 브랜치에서 작업을 주로 합니다. 이렇게 작업을하고 upstream/main브랜치로 머지하죠. 만약 또 작업할 일이 생겼다면 마찬가지로 upstream/main에서 브랜치를 분리해서 origin 브랜치에 작업을 합니다.
이 사이클에서 굳이 origin/main을 최신 코드로 업데이트 할 필요가 없습니다.

얘기가 조금 복잡해 보이긴하네요.. 혹시 이해하는데 도움이 되지 않았다면 커맨트나 DM으로 말씀주세요~

2021-01-28 13:37 UTC, Kihyun92 approved these changes
이번 과제를 진행하며 많은 고민들을 해보신 것 같아요 ㅎㅎ

특히 동료들과 생각을 공유하는 점이 좋았습니다 👍🏼 

처음 코드와 지금 코드가 어떻게 달라졌나요? 한번 정리해보셔도 좋을 것 같습니다 :)

2021-01-31 14:54 UTC, merged