컴포넌트 분리 완료.
CodeSoom/react-week2-assignment-1 pull request #68
Opened 2021-01-26 21:09 UTC by loyu78

컴포넌트 분리까지 완료 했으며, 코드 변경 예정입니다.

2021-01-27 13:27 UTC, Kihyun92 reviewed
좋은데요? 👍🏼  관심사에 따라 분리를 잘 해보고 계신 것 같아요 ㅎㅎ

2021-01-27 13:27 UTC, Kihyun92 requested changes

2021-01-27 13:27 UTC, Kihyun92 commented on src/index.jsx
> +import App from './App';
리액트 라이브러리 임포트와 로컬 컴포넌트 임포트를 구분하기 위해한 줄 공백을 주시면 좋을 것 같습니다! 지금은 모듈이 별로 없지만, 모듈 간에도 역할이 있고, 분리를 해두는 습관을 두면 좋을 것 같아요

다른 파일들도 적용해주세요~

2021-01-27 14:54 UTC, loyu78 commented on src/index.jsx
> +import App from './App';
분리 완료 했습니다!

2021-01-28 13:08 UTC, Kihyun92 requested changes

2021-01-28 13:08 UTC, Kihyun92 commented on src/Buttons.jsx
> +  const numbers = [1, 2, 3, 4, 5];
이 부분은 Buttons 함수 밖으로 분리해도 될 것 같아요.

이렇게 하면 Buttons 컴포넌트가 rerendering 될때마다 새로 선언과 할당을 하게 될 것 같아요.

2021-01-28 13:08 UTC, Kihyun92 commented on src/Button.jsx
> +    <button type="button" onClick={() => onClick(children)}>
```suggestion
    <button type="button" onClick={onClick}>
```

onClick의 인자로 children을 넘겨줄 이유가 있을까요?

단순하게 버튼 컴포넌트에서는 버튼 클릭이 있을때 넘겨받은 클릭 함수만 실행해주도록 해도 될 것 같아요. 
children을 넘기게 되면 우리가 의도치 않은 버튼 컴포넌트를 사용하는 쪽에서 넘기는 값을 전달하게되어 사이드 이펙트가 발생할 수 있을 것 같아요.

2021-01-29 12:56 UTC, Kihyun92 commented
@loyu78 님~ 커맨트 확인 부탁드려요 :)

2021-01-30 13:03 UTC, Kihyun92 approved these changes
처음 코드와 비교해서 어떻게 달라졌나요? 과제 풀이 영상은 꼭 보시면 좋겠습니다~

2021-01-31 14:22 UTC, merged