Create counter app with react
CodeSoom/react-week2-assignment-1 pull request #71
Opened 2021-01-27 12:11 UTC by gimsesu

이제 시작했습니다.. 성실하게 따라가겠습니다.

2021-01-27 13:33 UTC, Kihyun92 commented
좋습니다~ 다음 커밋 기다리겠습니다 💪

2021-01-27 13:57 UTC, Kihyun92 commented
두개의 풀 리퀘스트가 있네요! #72

하나의 PR로 관리해주세요~

2021-01-28 13:00 UTC, Kihyun92 reviewed
좋습니다 ㅎㅎ 

이제 컴포넌트를 분리하는 일만 남았네요 ㅎㅎ
다음 커밋 기다리겠습니다~

2021-01-29 13:24 UTC, Kihyun92 requested changes
컴포넌트가 하나의 파일에 모두 들어가 있는 것 같아요. 한 파일에는 하나의 컴포넌트만 있도록 분리해주세요

각 컴포넌트의 관심사에 대해서 생각해보며 분리하시면 좋겠습니다 :)
이미 보셨겠지만, 관심사 분리라는 용어가 이해가 안될땐 아샬님의 커멘트 참고해주세요~
- https://codesoom-group.slack.com/archives/C01JEHR319T/p1611840817112900?thread_ts=1611831049.059000&cid=C01JEHR319T

2021-01-29 13:24 UTC, Kihyun92 commented on src/index.jsx
> +  }
이 상태와 상태를 변경하는 함수를 어디서 관리하는게 좋을까요? ㅎㅎ 가능하면 상위에서 상태를 관리하고, 사용하는 곳에 넘겨주는 방식은 어떤가요?

2021-01-29 14:55 UTC, Kihyun92 commented
> state 관련 함수들을 App 내부가 아닌 별도의 컴포넌트로 분리하고 싶은데, 혹시 가능할까요?

어떤 방식으로 분리를 하고 싶으신가요? `App > 별도 컴포넌트 > 자식 컴포넌트`와 같은 순서일까요?

그리고 커밋에 질문을 남겨두시면 리뷰할 때 놓칠 수 있어요 ㅎㅎ 가능하면 풀리퀘스트 내에 댓글로 남겨주시면 좋을 것 같습니다 ㅎㅎ

2021-01-29 14:58 UTC, Kihyun92 commented
질문을 많이해주셔서 너무 좋네요 💯 

가능하면 슬랙 채널에 남겨주시면 다른 분들에게 더 도움이 되고 본인에게도 많은 도움이 될 것 같아요 😊

2021-01-29 15:02 UTC, Kihyun92 requested changes

2021-01-29 15:02 UTC, Kihyun92 commented on src/index.jsx
> +    <button type="button" onClick={() => { onClick(value); }}>
이렇게만 처리해도 될 것 같네요~
```suggestion
    <button type="button" onClick={() => onClick(value)}>
```

2021-01-29 15:02 UTC, Kihyun92 commented on src/index.jsx
> +  const { value, onClick } = props;
이렇게 처리해줘도 될 것 같아요 ㅎㅎ
```suggestion
function Button({ value, onClick }) {
```

2021-01-30 12:10 UTC, gimsesu commented
현재 onClick 함수들은 App() 내부에서 선언하여 사용하고 있습니다.

저는 App을 단순히 모든 컴포넌트들을 받는 그릇으로 보고 있어서,

onClick 함수들 또한 ButtonClickme나 ButtonNumber처럼 외부로 분리하고,

별도의 컴포넌트로서 호출을 할 수 있을지 궁금합니다. 구글링을 하고 있지만 검색 스킬이 부족한 것인지 
적절한 방법을 아직 찾지 못했습니다 ^^;

2021-01-30 13:00 UTC, Kihyun92 commented
추후에 redux와 같은 상태 관리 라이브러리를 배울 텐데, 그 필요성에 대해 미리 고민해보신 것 같아요! 💯 

뭐든 적절하게잘 사용하면 되는 것 같아요 ㅎㅎ 지금의 경우엔 관리할 상태가 하나밖에 없어서, 이걸 상태관리를 따로 하는게 조금 복잡해질 가능성이 있어서 따로 말씀은 안드렸었습니다.

redux, mobx 등 상태관리 라이브러리들을 봐보셔도 좋고, [flux 아키텍쳐](https://haruair.github.io/flux/docs/overview.html)에 대해서도 알아보시면 도움 될 것 같습니다.

2021-01-30 13:01 UTC, Kihyun92 commented
강의 풀이 영상을 보시고 아샬님은 어떻게 접근하시는지 봐보시면 좋을 것 같습니다~

2021-01-30 13:01 UTC, Kihyun92 approved these changes

2021-01-31 13:50 UTC, merged