Create Counter App
CodeSoom/react-week2-assignment-1 pull request #78
Opened 2021-01-29 17:01 UTC by hhjin015

Create Counter App by spliting components.

2021-01-30 12:19 UTC, Kihyun92 commented
> Create Counter App by splitting components.
> 
> import 할 때 .jsx를 명시해주지 않으면 module not found 에러가 뜹니다ㅜㅜ

 webpack의 extensions에 처리를 해둬서 웹팩에서 알아서 해당 확장자들은 처리를 해줄 텐데 이상하네요. 🤔
``` javascript
resolve: {
  extensions: ['.js', '.jsx'],
}
```

저는 지금 혜진님 코드 받아서 해봤는데, 지워도 에러가 발생하지 않아서요.

혹시 지금도 발생하나요?

2021-01-30 12:28 UTC, Kihyun92 requested changes
좋습니다. 굉장히 잘 분리해주신 것 같아요~

조금 더 고민해보셔도 좋고, 과제 풀이 영상을 보면서 특히 아샬님은 어떻게 문제를 풀어나가는지 풀이과정을 눈여겨 보시면 좋을 것 같습니다.

2021-01-30 12:28 UTC, Kihyun92 commented on src/App.jsx
> +import ButtonGroup from './ButtonGroup.jsx';
리액트 라이브러리 임포트와 로컬 컴포넌트 임포트를 구분하기 위해한 줄 공백을 주시면 좋을 것 같습니다! 지금은 모듈이 별로 없지만, 모듈 간에도 역할이 있고, 분리를 해두는 습관을 두면 좋을 것 같아요

다른 파일들도 적용해주세요~

2021-01-30 12:28 UTC, Kihyun92 commented on src/Button.jsx
> +function Button({ plus, num, setNum }) {
num 과 같이 줄여서 사용하는것 보다는 number로 사용하는건 어떤가요?

우리가 많이 줄여서 사용하는 부분이긴 하지만, 같이 코드를 작업하는 동료들은 이 부분을 다르게 생각할 수 있습니다.

이번 과제의 제한 조건 중에도 `함수 이름과 변수 이름에 줄임말은 사용하실 수 없습니다. 길더라도 명확하게 써주세요.` 가 있으니 수정하면 좋을 것 같네요~

2021-01-30 12:28 UTC, Kihyun92 commented on src/Button.jsx
> +  }
이 컴포넌트의 관심사는 무엇일까요?

지금은 기능이 많지 않아 사이드 이펙트가 없지만, 추후 기능이 확장 됐을때 setNum을 통해 상태를 변경하는 부분이 이곳저곳에 있음으로써 상태가 어떻게 변경될지 예측이 불가능해질 것 같아요~

2021-01-30 12:28 UTC, Kihyun92 commented on src/ButtonGroup.jsx
> +function ButtonGroup({ num, setNum }) {
Buttons 라는 네이밍은 어떤가요?

2021-01-31 15:06 UTC, Kihyun92 approved these changes
좋습니다. 네이밍 관련해서 리뷰를 조금 남겼네요 ㅎㅎ

변수명을 짓는게 정말 어렵죠. 하지만 그만큼 중요한 부분 같아요.
지금은 로직이 단순해서 의도를 파악하기 쉽지만, 조금만 기능이 추가되거나 코드의 양이 많아진다면 명확하고 의미를 잘 전달하는 네이밍이 중요해 질거에요.

2021-01-31 15:06 UTC, Kihyun92 commented on src/App.jsx
> +    setNumber(number + plus);
`plus` 라는 네이밍이 아니더라도 함수 내부 로직을 봐도 더해지는 인자인 것을 알 수 있을 것 같아요. `value`는 어떤가요?

2021-01-31 15:06 UTC, Kihyun92 commented on src/Buttons.jsx
> +const arr = [
arr 보다는 `numbers`같은 조금 더 의미있는 변수명이 좋겠어요.

2021-02-01 13:33 UTC, Kihyun92 commented
@hhjin015 님, 현재 CI 에러도 확인해보시고 처리해주세요~

항상 PR을 보내시고 CI가 잘 통과 됐는지 확인부탁드립니다 :) 

수정 되는대로 머지할게요~

2021-02-02 06:36 UTC, hhjin015 commented
기현님!! simple_test.js 에서 오류가 나는데 어떻게 하면 좋을까요?!

2021년 2월 1일 (월) 오후 10:33, Kihyun <notifications@github.com>님이 작성:

> @hhjin015 <https://github.com/hhjin015> 님, 현재 CI 에러도 확인해보시고 처리해주세요~
>
> 항상 PR을 보내시고 CI가 잘 통과 됐는지 확인부탁드립니다 :)
>
> 수정 되는대로 머지할게요~
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CodeSoom/react-week2-assignment-1/pull/78#issuecomment-770859818>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM7EWRZ7J6L2VLA3547JOSTS42UTXANCNFSM4WZFQUIQ>
> .
>

2021-02-02 12:23 UTC, Kihyun92 commented
PR 하단에 details를 통해 확인해보면 어떤 케이스에서 오류가 발생하는지 나옵니다.
![image](https://user-images.githubusercontent.com/35797540/106599647-b28fbc80-659c-11eb-9d55-556c0dbcab18.png)
혹은 로컬에서 `npm run test:e2e`를 실행해보시면 어느 부분에서 e2e 테스트를 실패하는지 나오니 확인부탁드려요 ㅎㅎ

2021-02-03 12:15 UTC, Kihyun92 approved these changes
끝까지 잘해주셨어요 ㅎㅎ
고생하셨습니다~

2021-02-03 12:15 UTC, Kihyun92 commented on jsconfig.json
> +}
![image](https://user-images.githubusercontent.com/35797540/106745668-cbfc3b80-6664-11eb-95e4-4e9a31202d74.png)

파일 끝에는 항상 공백을 추가해주세요~

2021-02-03 12:15 UTC, merged