2주차 1번째 과제
CodeSoom/react-week2-assignment-1 pull request #83
Opened 2021-05-10 01:29 UTC by yujong-lee

eslint와 인수테스트를 모두 통과합니다.
Counter 컴포넌트 안에 있는 내용에서 또 분리가 필요한 부분이 있는지 등 코드를 개선할 수 있는 방안을 더 생각하고 있습니다.

(실수로 main브랜치에 PR을 보내서 바로 close했습니다.)

2021-05-10 14:44 UTC, Kihyun92 requested changes
컴포넌트 분리를 잘 해주신 것 같아요! 👍🏼  함수들의 처리도 잘 해주신 것 같구요 :) 매직 리터럴 제거까지 👍🏼 👍🏼 

다만 App 컴포넌트의 역할은 매우 단순해보이고, Counter 컴포넌트는 꽤 많은 역할을 하고 있는 것 같습니다. 

지금은 복잡하지 않지만, 별도의 기능이 추가된다면 Counter 컴포넌트는 금방 복잡해질 것 같아요.

관심사 측면에서 각 컴포넌트의 역할을 조금 더 고민해보시면 좋을 것 같습니다 😊

2021-05-10 14:44 UTC, Kihyun92 commented on src/Counter.jsx
> +  }
```suggestion
  const { count } = state;
  
  function increaseCount(step) {
    setState({
      count: count + step,
    });
  }
```

표현 방식의 차이겠지만, 상위에서 구조분해할당을 한 뒤에 사용하는 방법도 가독성에 좋을 것 같군요

2021-05-11 00:05 UTC, yujong-lee commented on src/index.jsx
> +import App from './App';
`de32ba4`커밋으로 반영했습니다.

2021-05-11 00:12 UTC, yujong-lee commented on src/Counter.jsx
> +  const [state, setState] = useState(initialState);
제가 어제 읽은 리펙토링 책에서 [6.4 변수 인라인하기](https://refactoring.com/catalog/inlineVariable.html)가 생각나네요 ㅎㅎ. 

```javascript
const [count, setCount] = useState(0);
```

이렇게 바꿀 생각도 했었는데 이 [말씀](https://github.com/CodeSoom/react-week2-assignment-2/pull/70#discussion_r629481747)을 듣고 나니까 추후 관리할 변수들이 추가되었을 때의 확장성을 고려하면 그대로 두는 것이 맞을 것 같네요. `c727429`로 수정했습니다.

2021-05-11 00:30 UTC, yujong-lee commented on src/Counter.jsx
> +  }
이 부분은 조금 고민이 되네요. 제 생각은 이렇습니다. 

먼저 `increaseCount`부분은 `set`함수에 콜백을 주는 것이 이전 값을 활용해 다음값을 계산한다는 것이 더 명시적으로 느껴집니다. 만약 `state.count`값이 많이 재사용된다면 상위에서 미리 구조분해할당하는 것이 좋을 것 같은데 `increaseCount`부분 외에는 아래 부분 하나만 재사용됩니다.

```javascript
<Button
  value={`Click me! (${state.count})`}
  onClick={() => increaseCount(1)}
/>
```

그런데 이 버튼 부분은 리펙터링 책의 변수 인라인하기의 예시와 유사해보입니다. 아래는 그 예시입니다.
```javascript
// 이전
let basePrice = anOrder.basePrice;
return (basePrice > 1000);

// 이후
return anOrder.basePrice > 1000;
```
저자는 이를 `변수는 대체로 긍정적인 효과를 주지만, 그 이름이 원래 표현식과 다를 바 없을 때도 있다.` 라고 설명합니다. 

이러한 이유로 저는 그대로 두는 것이 더 나은 것 같은데 트레이너님의 의견은 어떠신가요?

2021-05-11 01:27 UTC, yujong-lee commented on src/Counter.jsx
> +  }
이 코멘트를 작성한 뒤에 [2번째 과제](https://github.com/CodeSoom/react-week2-assignment-2/pull/70#discussion_r629481747)를 수정하면서 

```javascript
const [state, setState] = useState({
  userInput: '',
  tasks: [],
});

const { userInput, tasks } = state;
```

제안해주신 방식으로 코드를 짜봤는데 이 경우에는 반복이 많으니 이런식으로 하는게 확실히 좋네요. 
코드의 복잡도가 늘어날수록 제안해주신 쪽이 더 낫다고도 느껴지네요.

2021-05-11 02:15 UTC, yujong-lee commented
> 지금은 복잡하지 않지만, 별도의 기능이 추가된다면 Counter 컴포넌트는 금방 복잡해질 것 같아요.
> 관심사 측면에서 각 컴포넌트의 역할을 조금 더 고민해보시면 좋을 것 같습니다 😊

`b7ee7ec`에서 `Container 컴포넌트`와 `Presentational 컴포넌트`를 도입하여 분리했습니다.

2021-05-11 14:31 UTC, Kihyun92 commented on src/Counter.jsx
> +  }
말씀하신대로 관리하는 상태가 적을 경우에는 작성하신 것처럼 콜백을 사용한 방식이 의도가 더 드러날 수 있을 것 같습니다 👍🏼 

코드의 의도와 가독성 등 여러 관점에서 고민해보시고 적용해주셨군요 :)

저도 유종님 덕분에 코드의 복잡도에 따라 어떤 방식이 좋은지 이번 기회에 고민해볼 수 있었네요. 🙏🏻

2021-05-12 00:56 UTC, yujong-lee commented
무슨 말씀인지는 이해했습니다. `51471c5`로 수정했습니다.

저도 컨테이너까지 도입하는 것은 좀 과하다고 생각은 했습니다. 그럼에도 한 것은 저는 `App`에서 `Counter`의 상태를 관리하는 것이 좀 부적절하다고 생각했습니다. 만약 여기서 말하는 `앱`이 `카운터앱`을 말하는 것이라면 그럴 수 있다고 생각합니다. (쓰고 나니까 그냥 이것이 의도였나 싶습니다. ㅎㅎ)

그런데 이 앱이 여러가지 일을 할 수 있는데 그 중 하나가 `Counter`이라면 `App`에서 `Counter`의 상태관리를 하는 것은 부자연스럽지 않나요? `Counter`에 관련된 상태라면 `Counter`에서 처리하는 것이 맞지 않을까 하고 느껴집니다.

제가 조금 잘못된 개념을 가지고 있나 싶습니다. 예를 들어 아래는 제가 예전에 만든 서비스의 `App`인데, 이 `웹앱`에는 `로그인페이지`와 `튜토리얼페이지`가 있으므로 그것을 넣어준 것이 전부입니다. 로그인과 관련 된 일은 `로그인페이지`가 하고, 튜토리얼과 관련 된 일은 `튜토리얼 페이지`가 하겠죠.  만약 여기 `App`에서 `useState`으로 상태를 선언해야한다면 그것은 `튜토리얼페이지`와 `로그인페이지`에서 둘 다 쓰이는 것일텐데, 그러면 그것은 `context`나 `redux` 등을 사용하는 것이 맞지 않나 생각합니다.

```js
function App() {
  return (
    <RecoilRoot>
      <BrowserRouter>
        <Switch>
          <Route path='/demo'>
            <TutorialPage/>
          </Route>
          <Route path='/'><LoginPage/></Route>
        </Switch>
      </BrowserRouter>
    </RecoilRoot>
  );
}

export default App;
```

2021-05-12 16:11 UTC, Kihyun92 commented
제가 조금 혼동을 드린 것 같네요. 😅

잘 알고 계신 것 같습니다. 말씀하신대로 지금은 카운터 앱이기 때문에 App에서 관리해도 괜찮을 것 같아 말씀 드렸던 부분이에요.
만약 여러 기능을 하는 앱이라면, 예시로 보여주신 코드처럼 App 컴포넌트는 각 기능을 노출하는 역할을 할테고, 각각의 기능 컨테이너에서 상태를 관리하는게 맞겠죠 :)

정말 많은 고민을 해보면서 작업해보시는 것 같아 좋습니다 👍🏼

2021-05-12 16:21 UTC, Kihyun92 requested changes

2021-05-12 16:21 UTC, Kihyun92 commented on src/Counter.jsx
> +      ))}
key 값을 추가해주세요~

2021-05-12 16:21 UTC, Kihyun92 commented on src/app.jsx
> +  function increaseCount(step) {
App 컴포넌트의 관점에서는 이 함수는 단순히 count 상태값에 넘어온 값을 더해주는 부분이라 step이라는 인자명이 개인적으로는 명확하지 않다는 느낌이 들어요.

혹시 step 으로 인자의 이름을 한 이유가 있을까요? 제가 아는 단어로 유추해봤을땐 이 경우엔 단계 로 해석이 되어서요 😅 
(의도와 다르다면 지적 부탁드립니다!)

2021-05-13 01:16 UTC, yujong-lee commented on src/app.jsx
> +  function increaseCount(step) {
`Counter.jsx`에서도 `steps`를 사용했는데요. `step`을 걸음걸이라는 의미로 생각해서 그렇게 했습니다.
그런데 말씀하신대로 `App.jsx`에서는 그냥 넘어온걸 더해주기만 하는거라 `value`같은게 더 적절하겠습니다.

오히려 `Counter.jsx`의 아래코드에서 `value`를 `step`으로 바꾸는게 좋겠네요.
```js
{steps.map((value) => (
  <Button
    value={value}
    onClick={() => increaseCount(value)}
  />
))}
```

2021-05-13 01:26 UTC, yujong-lee commented
```js
Button.propTypes = {
  value: PropTypes.number.isRequired,
  onClick: PropTypes.func.isRequired,
};
```
이렇게 타입을 지정해주는 부분이 꼭 필요할까요? 타입이 중요하다면 그냥 타입스크립트를 쓰면 되고, 특이 이런 작은 앱에서는 불필요한 것 같아요. `eslint`때문에 작성했었는데, `eslintrc.js` 의 `rules`에 `'react/prop-types': 'off'` 를 설정해서 제거할까하는 생각이 듭니다. 실제 개발하실 때 `propTypes` 많이들 사용하시나요?

2021-05-13 01:27 UTC, yujong-lee commented on src/Counter.jsx
> +      ))}
아 `key`를 자꾸 빠트리네요. `54ab99e`으로 추가했습니다.

2021-05-13 14:03 UTC, Kihyun92 commented
> ```js
> Button.propTypes = {
>   value: PropTypes.number.isRequired,
>   onClick: PropTypes.func.isRequired,
> };
> ```
> 
> 이렇게 타입을 지정해주는 부분이 꼭 필요할까요? 타입이 중요하다면 그냥 타입스크립트를 쓰면 되고, 특이 이런 작은 앱에서는 불필요한 것 같아요. `eslint`때문에 작성했었는데, `eslintrc.js` 의 `rules`에 `'react/prop-types': 'off'` 를 설정해서 제거할까하는 생각이 듭니다. 실제 개발하실 때 `propTypes` 많이들 사용하시나요?

과제 시작 전에 rule 이 잘못 제거 됐던 것 같네요😅

저도 거의 타입스크립트로 작업을 했고, 만약 자바스크립트만 사용해야한다면 유용할 것 같다는 생각이 들어요. 

본인의 선택에 따라 룰을 추가해서 off 하셔도 좋고, 그대로 진행해보셔도 좋을 것 같네요 :)

2021-05-13 14:08 UTC, Kihyun92 requested changes
이번 과제의 의도에 맞게 잘 진행해주신 것 같아요. 👍🏼 

파일, 컴포넌트 네이밍만 변경하면 될 것 같군요! 확인 부탁드립니다.😊

2021-05-13 14:08 UTC, Kihyun92 commented on src/Counter.jsx
> +export default function CounterContainer({ count, increaseCount }) {
파일명과 컴포넌트명은 일치시켜주는게 좋을 것 같아요~

2021-05-13 14:08 UTC, Kihyun92 commented on src/app.jsx
> +export default function App() {
파일명을 App.jsx로 변경해주는게 좋을 것 같네요~

2021-05-13 14:08 UTC, Kihyun92 commented on src/app.jsx
> +      ...state,
`...state`는 추후 확장을 고려해서 추가하신건가요? 지금은 필요 없을 것 같아요.

2021-05-13 23:48 UTC, yujong-lee commented on src/app.jsx
> +export default function App() {
이게 이상하게 제 시스템에는 `App.jsx`로 되어있는데, 반영이 안되었네요.
비슷한 문제를 겪는 사람이 많아보이는데, [여기](https://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git)를 참고해서 `8521bdf`로 해결했습니다.

2021-05-13 23:50 UTC, yujong-lee commented on src/Counter.jsx
> +export default function CounterContainer({ count, increaseCount }) {
`010fac3`로 수정했습니다.

2021-05-14 00:16 UTC, yujong-lee commented on src/app.jsx
> +      ...state,
넵. 당장은 필요하지 않지만 확장을 고려해야 한 것인데, 여기서는 워낙 간단한 앱이라서 뺴도 될 것 같네요. `f9cf8eb`로 수정했습니다.

2021-05-14 14:38 UTC, Kihyun92 approved these changes
고생하셨습니다! approve 하겠습니다~

2021-05-17 15:29 UTC, merged