2주차 과제1 (카운터 앱 만들기)
CodeSoom/react-week2-assignment-1 pull request #84
Opened 2021-05-10 07:10 UTC by seong-dodo

안녕하세요.
2주차 과제1(카운터앱) 1차 PR 올립니다.

강의를 보고 따라하면 작업  단위를 쪼개서 `commit`을 해보았습니다.
우선, `index.jsx` 와 `App.jsx` 파일을 분리하여 카운터 앱 기능을 완성시켰습니다.

####  관심사 분리하여 한 파일에 하나의 컴포넌트만 있도록 만들어서 올리겠습니다 😆

2021-05-10 08:32 UTC, seong-dodo commented
관심사 분리하여 완성하였습니다 😀

2021-05-10 15:01 UTC, Kihyun92 requested changes
오우 깔끔하게 너무 잘해주셨네요 👍🏼 👍🏼 

그런데 라인에 스페이스가 4칸이 띄워진 것 같은데 맞나요?

과제 프로젝트의 린트 설정이 2칸 공백으로 되어있습니다. 한번 확인 부탁드려요~

2021-05-11 14:54 UTC, Kihyun92 reviewed
이번 과제의 의도에 맞게 잘 적용해주셨네요 👍🏼 👍🏼 

커맨트 드린 내용 말고는 더 리뷰할 부분이 없는 것 같습니다 😊

2021-05-12 12:53 UTC, seong-dodo commented
오늘 PR이 조금 늦었습니다.

2021-05-12 15:12 UTC, Kihyun92 commented
린트 에러가 나는것 같아요. 확인 부탁드립니다~

2021-05-13 13:39 UTC, seong-dodo commented
https://github.com/CodeSoom/react-week2-assignment-1/pull/84#discussion_r630246357
이부분에 제가 댓글남겼는데 `pending` 되어 다시 문의드립니다~ 
> 확장자명(.jsx)을 제거해도 기본적으로 호환이 되는걸로 알고 있는데 혹시 다른 방법이 있나요??

그리고 부끄럽지만 린트 동작 확인하는법을 방금 알게 되었어요 ㅜㅜ
`npx eslint --fix .` 을 해도 아무것도 안 나타나서 에러가 없는 줄 알았어요 ㅠㅠㅠ
그래서 설치도 다시해보고 구글 검색도 해보고.. 도저히 안되겠다! 
DM을 보내야 하나 고민하던 찰나에 README 살펴보니 명령어가 따로 설정되어 있는것을 발견했어요 😿 😿 😿 
에러 수정 중인데 도저히 이해가 안되는 부분이 있어 문의드려요😭 

Buttons 컴포넌트, Counter 컴포넌트, Page 컴포넌트에서
 - 'count' is missing in props validation
 - 'onClick' is missing in props validation 
 이렇게 뜨는 걸 어떻게 해결해야 하는건지 이해가 되지 않습니다 ㅠㅠ

2021-05-13 14:11 UTC, Kihyun92 commented
> [#84 (comment)](https://github.com/CodeSoom/react-week2-assignment-1/pull/84#discussion_r630246357)
> 이부분에 제가 댓글남겼는데 `pending` 되어 다시 문의드립니다~
> 
> > 확장자명(.jsx)을 제거해도 기본적으로 호환이 되는걸로 알고 있는데 혹시 다른 방법이 있나요??
> 
> 그리고 부끄럽지만 린트 동작 확인하는법을 방금 알게 되었어요 ㅜㅜ
> `npx eslint --fix .` 을 해도 아무것도 안 나타나서 에러가 없는 줄 알았어요 ㅠㅠㅠ
> 그래서 설치도 다시해보고 구글 검색도 해보고.. 도저히 안되겠다!
> DM을 보내야 하나 고민하던 찰나에 README 살펴보니 명령어가 따로 설정되어 있는것을 발견했어요 😿 😿 😿
> 에러 수정 중인데 도저히 이해가 안되는 부분이 있어 문의드려요😭
> 
> Buttons 컴포넌트, Counter 컴포넌트, Page 컴포넌트에서
> 
> * 'count' is missing in props validation
> * 'onClick' is missing in props validation
>   이렇게 뜨는 걸 어떻게 해결해야 하는건지 이해가 되지 않습니다 ㅠㅠ

해당 에러는 prop에 대한 타입을 지정해달라는 에러인데, 이 부분은 룰을 추가해서 off 하셔도 좋고, 직접 propTypes를 추가해주셔도 좋습니다.
- https://ko.reactjs.org/docs/typechecking-with-proptypes.html

2021-05-13 14:25 UTC, Kihyun92 approved these changes
과제의 의도에 맞게 너무 잘 진행해주셨네요 👍🏼  과제 approve 하겠습니다~

이번 과제를 통해 어떤걸 배웠는지 떠올려보셔도 좋을 것 같습니다 ㅎㅎ

2021-05-13 15:02 UTC, seong-dodo commented
덕분에 제가 아직 부족한 부분을 많이 채울 수 있었습니다 💃  감사합니다 🙏 
이번 과제를 통해 배운 내용을 차곡차곡 잘 정리해볼게요 👏  👏  👏  👏  👏

2021-05-17 15:36 UTC, merged