과제 2-1 제출
CodeSoom/react-week2-assignment-1 pull request #88
Opened 2021-05-12 02:42 UTC by studioLuda

2021-05-12 16:35 UTC, Kihyun92 requested changes
`index.jsx`는 진입점으로 컴포넌트는 아닙니다. App은 컴포넌트입니다 :)

2021-05-12 16:35 UTC, Kihyun92 commented on src/components/Button.jsx
> +Button.prototype = {
`prototype`에 접근하는게 맞나요? `propTypes`가 맞을 것 같군요.

2021-05-12 16:35 UTC, Kihyun92 commented on src/components/Buttons.jsx
> +            }}
인라인 함수가 한줄로 표현이 가능하다면 이렇게 해주는게 좋을 것 같네요.
```suggestion
            onClick={() => onClick(number)}
```

2021-05-12 16:35 UTC, Kihyun92 commented on src/index.jsx
> +  const numbers = [1, 2, 3, 4, 5];
App 컴포넌트에서 numbers를 알 필요가 있을까요? App 컴포넌트의 관심사는 무엇인가요?

2021-05-12 16:35 UTC, Kihyun92 commented on src/index.jsx
> +import Counter from './pages/counter';
```suggestion
import React, { useState } from 'react';
import ReactDOM from 'react-dom';

import Counter from './pages/counter';
```
리액트 라이브러리 import와 로컬 컴포넌트 import 를 구분하기 위해 한 줄 공백을 주시면 좋을 것 같습니다~

지금은 모듈이 별로 없지만, 모듈 간에도 역할이 있고, 분리를 해두는 습관을 두면 좋을 것 같습니다 :)

2021-05-13 02:20 UTC, studioLuda commented on src/components/Button.jsx
> +Button.prototype = {
머쓱타드 입니다 :) ㅎㅎ  오타 및 자동완성에 더 주의하겠습니다.!!

2021-05-13 02:39 UTC, studioLuda commented
피드백 반영 완료 하였습니다!

 * 1) index.jsx는 진입점으로 컴포넌트는 아닙니다. App은 컴포넌트입니다 :)
   서브 미션 : 진입점과 컴포넌트 차이 이해. App이 컴포넌트인 이유 생각하고 공부하기
 
 * 2) prototype에 접근하는게 맞나요? propTypes가 맞을 것 같군요.
  서브 미션 : 컴포넌트.propTypes 작성 깊이 알기. (isRequired, defaultProps)
  참고     : https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/require-default-props.md
 
 * 3) App 컴포넌트에서 numbers를 알 필요가 있을까요? App 컴포넌트의 관심사는 무엇인가요?
    서브 미션 : Buttons 컴포넌트명 더 명확하게 바꾸기
 
 * 4) 인라인 함수가 한줄로 표현이 가능하다면 이렇게 해주는게 좋을 것 같네요.
 * 5) 리액트 라이브러리 import와 로컬 컴포넌트 import 를 구분하기 위해 한 줄 공백을 주시면 좋을 것 같습니다~
   지금은 모듈이 별로 없지만, 모듈 간에도 역할이 있고, 분리를 해두는 습관을 두면 좋을 것 같습니다 :)
 
   공통 미션 : 늘 다른사람이 보아도 쉽게 읽히도록 정리하기.
 
감사합니다!!

2021-05-13 14:22 UTC, Kihyun92 approved these changes
과제의 의도에 맞게 잘 진행해주신 것 같아요 👍🏼 

`propTypes`를 다루기 위해 깊이 아시는 것 보다,`javascript`에서 타입 체킹이 왜 중요할지, 어떤 이점이 있는지를 고민해보시는 게 좋을 것 같아요

사실 타입이 필요하다면 `Typescript`라는 좋은 대안이 있으니까요.

2021-05-17 15:33 UTC, merged