아직 propType 을 왜정해야하는지,string.isRequired 이부분은 왜사용하는지
CodeSoom/react-week2-assignment-1 pull request #91
Opened 2021-05-15 13:02 UTC by parkjun5

제대로 이해하지 못한것 같습니다..검색대로 그냥 쳤네요..

처음 직장다니면서 주중에는 강의만 듣고 문제를 풀지못하였네요..반성하겠습니다.

또, state에 대한 이해가 부족한것 같습니다.
그냥 setState를 count + ints 로 보낼때에는 바로 적용되는데,
처음 생각한 state에 value, count 두개의 값을 넣고 처리하는 방식은 제대로 처리가 안되는데 이부분이 이해가 되지 않는것 같습니다..

2021-05-15 14:30 UTC, Kihyun92 requested changes
급하게 진행하시다보니 어쩔 수 없는 부분인 것 같네요 😭

그래도 직접 해보신게 좋습니다 👍🏼 

질문 남겨주신 부분은 정확히 어떤 부분일까요? 참고할 수 있는 코드를 남겨주시면 감사하겠습니다~
> 또, state에 대한 이해가 부족한것 같습니다.
그냥 setState를 count + ints 로 보낼때에는 바로 적용되는데,
처음 생각한 state에 value, count 두개의 값을 넣고 처리하는 방식은 제대로 처리가 안되는데 이부분이 이해가 되지 않는것 같습니다..

2021-05-15 14:30 UTC, Kihyun92 commented on src/index.jsx
> +        />
key 값 추가가 필요해보입니다!

참고: [https://reactjs.org/docs/lists-and-keys.html](https://reactjs.org/docs/lists-and-keys.html)

2021-05-15 14:30 UTC, Kihyun92 commented on src/index.jsx
> +function App() {
`index.jsx`는 진입점으로 컴포넌트는 아닙니다. App은 컴포넌트입니다:)

2021-05-15 14:30 UTC, Kihyun92 commented on src/index.jsx
> +  function handelClick() {
상태 관리부분과 함수를 선언한 코드 사이에 공백을 추가해서 구분하면 좋을 것 같아요~

2021-05-15 14:30 UTC, Kihyun92 commented on src/index.jsx
> +  return (
사이에 공백을 추가해주면 좋을 것 같아요

2021-05-15 14:30 UTC, Kihyun92 commented on src/index.jsx
> +ReactDOM.render(
공백을 추가해주세요~

2021-05-15 14:30 UTC, Kihyun92 commented on src/index.jsx
> +import ButtonMaker from './components/buttonMaker';
```suggestion
import React, { useState } from 'react';
import ReactDOM from 'react-dom';

import ClickMeButton from './components/clickMeButton';
import ButtonMaker from './components/buttonMaker';

```
리액트 라이브러리 임포트와 로컬 컴포넌트 임포트를 구분하기 위해한 줄 공백을 주시면 좋을 것 같습니다! 지금은 모듈이 별로 없지만, 모듈 간에도 역할이 있고, 분리를 해두는 습관을 두면 좋을 것 같아요

다른 파일들도 적용해주세요~

2021-05-15 15:41 UTC, parkjun5 commented on src/index.jsx
> +        />
key값에 대해서 제가 잘못이해한것일까요?
저는 <button >태그를 사용하는 곳에서 key={value} 식으로 사용하는것이라고 생각하였는데,  혹시 저 방식과
<ButtonMaker
   key={value or int?}
/>
식으로 먼저 넣어주어야 하는 것과 차이는 무엇일까요?

2021-05-16 12:54 UTC, Kihyun92 commented on src/index.jsx
> +        />
`ButtonMaker` 컴포넌트 내부에서 key 값을 알 필요가 없습니다. key 지정을 하는 이유는 map 함수 내에서 key 값을 통해서 각 엘리먼트를 구분하기 위해서니까요 :)

이 부분을 참고하시면 될 것 같아요.
- https://ko.reactjs.org/docs/lists-and-keys.html#extracting-components-with-keys

2021-05-16 14:53 UTC, parkjun5 commented
key를 지정하는 방식 변경하여서 푸쉬하였습니다.

2021-08-08 07:47 UTC, merged